import type { Recette } from './types'

/**
 * Le déjeuner de l'ordonnance : une protéine, un quart d'assiette de
 * féculents, des légumes à volonté, une cuillère de matière grasse. Quantités
 * pour une personne.
 */
export const DEJEUNERS: Recette[] = [
  {
    id: 'poulet-citron',
    titre: 'Poulet au citron, haricots verts et pommes de terre',
    moment: 'dejeuner',
    minutes: 35,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole', 'economique'],
    ingredients: [
      { nom: 'Filet de poulet', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '2 moyennes', rayon: 'Fruits et légumes' },
      { nom: 'Haricots verts', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire les pommes de terre et les haricots verts à la vapeur, 20 minutes.',
      'Saisissez le poulet à la poêle avec l’ail écrasé, 6 minutes par face.',
      'Déglacez avec le jus de citron hors du feu.',
      'Servez le tout arrosé du jus de cuisson.',
    ],
  },
  {
    id: 'boeuf-poivrons',
    titre: 'Bœuf sauté aux poivrons et boulgour',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 490,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    ingredients: [
      { nom: 'Bavette de bœuf', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Boulgour', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Poivrons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignon', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites gonfler le boulgour dans deux fois son volume d’eau bouillante, 12 minutes.',
      'Émincez poivrons et oignon, faites-les revenir 10 minutes à feu vif.',
      'Ajoutez le bœuf coupé en lanières, 3 minutes suffisent.',
      'Mélangez au boulgour et servez.',
    ],
    saisons: ['ete', 'automne'],
  },
  {
    id: 'dinde-ratatouille',
    titre: 'Escalope de dinde, ratatouille et semoule',
    moment: 'dejeuner',
    minutes: 40,
    kcal: 460,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['batch', 'economique'],
    ingredients: [
      { nom: 'Escalope de dinde', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Semoule', quantite: '50 g crue', rayon: 'Épicerie' },
      { nom: 'Aubergine', quantite: '1 petite', rayon: 'Fruits et légumes' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Coupez les légumes en dés et faites-les mijoter 30 minutes à couvert.',
      'Poêlez l’escalope 5 minutes par face.',
      'Versez l’eau bouillante sur la semoule, couvrez 5 minutes, égrainez.',
      'Servez la ratatouille sur la semoule, l’escalope à côté.',
    ],
    astuce: 'La ratatouille se fait en grande quantité et se garde 4 jours au frais.',
    conservation: '4 jours au réfrigérateur',
    saisons: ['ete'],
  },
  {
    id: 'lentilles-oeufs',
    titre: 'Lentilles, œufs durs et carottes râpées',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 440,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique', 'nomade'],
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Lentilles vertes', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Échalote', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Moutarde', quantite: '1 cc', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez les lentilles 20 minutes dans l’eau non salée.',
      'Faites durcir les œufs 9 minutes.',
      'Râpez les carottes, assaisonnez avec l’huile et la moutarde.',
      'Servez les lentilles tièdes avec l’échalote émincée et les œufs coupés en deux.',
    ],
    astuce: 'Saler les lentilles en début de cuisson durcit leur peau — attendez la fin.',
    conservation: '3 jours au réfrigérateur',
  },
  {
    id: 'salade-pois-chiches',
    titre: 'Salade de pois chiches, feta et concombre',
    moment: 'dejeuner',
    minutes: 10,
    kcal: 450,
    couvre: ['proteine', 'feculent', 'legume', 'laitier', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson', 'nomade'],
    ingredients: [
      { nom: 'Pois chiches cuits', quantite: '150 g égouttés', rayon: 'Épicerie' },
      { nom: 'Feta', quantite: '40 g', rayon: 'Crèmerie' },
      { nom: 'Concombre', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Tomates cerises', quantite: '8', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Menthe fraîche', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Rincez les pois chiches à l’eau froide et égouttez-les bien.',
      'Coupez le concombre en dés et les tomates en deux.',
      'Mélangez le tout avec l’huile, le jus de citron et la menthe ciselée.',
      'Émiettez la feta par-dessus au moment de servir.',
    ],
    astuce: 'Elle se transporte sans dommage : la feta empêche la salade de rendre son eau.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'quinoa-saumon-fume',
    titre: 'Quinoa au saumon fumé et petits pois',
    moment: 'dejeuner',
    minutes: 20,
    kcal: 465,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['nomade', 'batch'],
    ingredients: [
      { nom: 'Quinoa', quantite: '60 g cru', rayon: 'Épicerie' },
      { nom: 'Saumon fumé', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Petits pois', quantite: '150 g', rayon: 'Surgelés' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Aneth', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Cuisez le quinoa 15 minutes dans deux fois son volume d’eau.',
      'Ajoutez les petits pois les 5 dernières minutes, directement dans la casserole.',
      'Égouttez, laissez tiédir, assaisonnez à l’huile et au citron.',
      'Ajoutez le saumon coupé en lanières et l’aneth.',
    ],
    conservation: '2 jours au réfrigérateur',
  },
]
