import type { Recette } from './types'

/**
 * Le déjeuner de l'ordonnance : une protéine, un quart d'assiette de
 * féculents, des légumes à volonté, une cuillère de matière grasse. Quantités
 * pour une personne.
 */
export const DEJEUNERS: Recette[] = [
  {
    id: 'poulet-citron',
    titre: 'Poulet au citron, haricots verts et pommes de terre',
    moment: 'dejeuner',
    minutes: 35,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole', 'economique'],
    cuisine: 'mediterraneenne',
    regimes: ['sans-gluten', 'sans-lactose'],
    substitutions: [
      {
        ingredient: 'Filet de poulet',
        par: 'escalope de dinde',
        effet: 'un peu plus sec, baissez de 1 min par face',
      },
    ],
    appareils: [
      {
        appareil: 'Air fryer',
        instructions: 'Pommes de terre en cubes 18 min à 190 °C, poulet ajouté à mi-parcours. Les haricots restent à la vapeur.',
      },
      {
        appareil: 'Cocotte',
        instructions: 'Tout ensemble à couvert, 25 min à feu doux. Le poulet ne dore pas mais reste plus moelleux.',
      },
    ],
    ingredients: [
      { nom: 'Filet de poulet', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '2 moyennes', rayon: 'Fruits et légumes' },
      { nom: 'Haricots verts', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire les pommes de terre et les haricots verts à la vapeur, 20 minutes.',
      'Saisissez le poulet à la poêle avec l’ail écrasé, 6 minutes par face.',
      'Déglacez avec le jus de citron hors du feu.',
      'Servez le tout arrosé du jus de cuisson.',
    ],
  },
  {
    id: 'boeuf-poivrons',
    titre: 'Bœuf sauté aux poivrons et boulgour',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 490,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'orientale',
    regimes: ['sans-lactose'],
    substitutions: [
      {
        ingredient: 'Bavette de bœuf',
        par: 'blanc de poulet',
        effet: '40 kcal de moins, 2 min de cuisson en plus',
      },
    ],
    ingredients: [
      { nom: 'Bavette de bœuf', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Boulgour', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Poivrons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignon', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites gonfler le boulgour dans deux fois son volume d’eau bouillante, 12 minutes.',
      'Émincez poivrons et oignon, faites-les revenir 10 minutes à feu vif.',
      'Ajoutez le bœuf coupé en lanières, 3 minutes suffisent.',
      'Mélangez au boulgour et servez.',
    ],
    saisons: ['ete', 'automne'],
  },
  {
    id: 'pates-thon-tomates',
    titre: 'Pâtes au thon et tomates cerises',
    moment: 'dejeuner',
    minutes: 15,
    kcal: 465,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['rapide', 'economique', 'une-casserole'],
    cuisine: 'italienne',
    regimes: ['sans-lactose'],
    substitutions: [
      {
        ingredient: 'Pâtes complètes',
        par: 'pâtes de légumineuses',
        effet: 'plus de protéines et de fibres, cuisson plus courte',
      },
    ],
    ingredients: [
      { nom: 'Thon au naturel', quantite: '1 boîte', rayon: 'Épicerie' },
      { nom: 'Pâtes complètes', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Tomates cerises', quantite: '10', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Basilic frais', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire les pâtes le temps indiqué sur le paquet.',
      'Coupez les tomates en deux et faites-les tomber 5 minutes à la poêle.',
      'Égouttez le thon, ajoutez-le hors du feu avec le jus de citron et l’huile.',
      'Mélangez aux pâtes, terminez au basilic.',
    ],
    astuce: 'Le thon au naturel plutôt qu’à l’huile fait 100 kcal d’écart pour la même boîte.',
    saisons: ['ete'],
  },
  {
    id: 'curry-pois-chiches',
    titre: 'Curry de pois chiches et riz',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 455,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique', 'une-casserole'],
    cuisine: 'indienne',
    regimes: ['vegan', 'sans-gluten', 'sans-lactose'],
    substitutions: [
      {
        ingredient: 'Lait de coco léger',
        par: 'yaourt nature hors du feu',
        effet: 'plus acide, moins gras — mais plus sans lactose',
      },
    ],
    rechauffage: 'À la casserole à feu doux avec deux cuillères d’eau. Le riz se réchauffe à part, couvert, au micro-ondes.',
    ingredients: [
      { nom: 'Pois chiches cuits', quantite: '150 g égouttés', rayon: 'Épicerie' },
      { nom: 'Riz basmati', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Lait de coco léger', quantite: '80 ml', rayon: 'Épicerie' },
      { nom: 'Épinards', quantite: '100 g', rayon: 'Surgelés' },
      { nom: 'Oignon', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Curry en poudre', quantite: '1 cc', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir l’oignon émincé avec le curry, 5 minutes.',
      'Ajoutez les pois chiches et le lait de coco, laissez mijoter 10 minutes.',
      'Jetez les épinards dedans en fin de cuisson, ils fondent en 2 minutes.',
      'Servez sur le riz cuit à part.',
    ],
    astuce: 'Doublez les quantités : ce curry est meilleur réchauffé le lendemain.',
    conservation: '3 jours au frais',
  },
  {
    id: 'wrap-poulet-crudites',
    titre: 'Wrap au poulet et crudités',
    moment: 'dejeuner',
    minutes: 10,
    kcal: 440,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['rapide', 'nomade', 'sans-cuisson'],
    cuisine: 'mexicaine',
    ingredients: [
      { nom: 'Galette de blé complet', quantite: '1', rayon: 'Boulangerie' },
      { nom: 'Filet de poulet', quantite: '100 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Carotte', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
      { nom: 'Fromage blanc 3 %', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Râpez la carotte, mélangez-la au fromage blanc citronné : c’est la sauce.',
      'Étalez sur la galette, ajoutez le poulet cuit émincé et la salade.',
      'Roulez serré et coupez en deux en biais.',
    ],
    astuce:
      'Le fromage blanc citronné remplace la mayonnaise pour 90 kcal de moins, et tient aussi bien.',
  },
  {
    id: 'riz-saute-oeufs',
    titre: 'Riz sauté aux œufs et petits pois',
    moment: 'dejeuner',
    minutes: 15,
    kcal: 450,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'economique', 'une-casserole'],
    cuisine: 'asiatique',
    regimes: ['sans-lactose'],
    substitutions: [
      {
        ingredient: 'Sauce soja',
        par: 'tamari',
        effet: 'sans gluten, goût plus rond',
      },
    ],
    appareils: [
      {
        appareil: 'Wok',
        instructions: 'Feu vif, riz de la veille bien froid : c’est ce qui l’empêche de coller. 4 min suffisent.',
      },
    ],
    ingredients: [
      { nom: 'Riz basmati', quantite: '60 g cru', rayon: 'Épicerie' },
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Petits pois', quantite: '100 g', rayon: 'Surgelés' },
      { nom: 'Carotte', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Sauce soja', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez le riz à l’avance et laissez-le refroidir : c’est ce qui l’empêche de coller.',
      'Faites sauter la carotte en dés et les petits pois, 6 minutes.',
      'Poussez sur le côté, cassez les œufs dans la poêle et brouillez-les.',
      'Ajoutez le riz et la sauce soja, mélangez à feu vif 2 minutes.',
    ],
    astuce: 'C’est la recette des restes : elle marche avec n’importe quel légume de la veille.',
  },
  {
    id: 'saumon-semoule-courgettes',
    titre: 'Saumon, semoule et courgettes rôties',
    moment: 'dejeuner',
    minutes: 30,
    kcal: 500,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'mediterraneenne',
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Pavé de saumon', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Semoule', quantite: '50 g crue', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: '1 moyenne', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Menthe fraîche', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Enfournez la courgette en rondelles 20 minutes à 200 °C avec l’huile.',
      'Ajoutez le saumon sur la même plaque pour les 10 dernières minutes.',
      'Gonflez la semoule dans son volume d’eau bouillante, 5 minutes.',
      'Servez avec le citron et la menthe ciselée.',
    ],
    astuce: 'Tout sur une seule plaque : un plat à laver, et le poisson prend le goût du légume.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'salade-lentilles-feta',
    titre: 'Salade de lentilles, feta et tomates',
    moment: 'dejeuner',
    minutes: 10,
    kcal: 455,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['sans-cuisson', 'nomade', 'vegetarien', 'batch', 'economique'],
    cuisine: 'mediterraneenne',
    regimes: ['sans-gluten'],
    rechauffage: 'Se mange froide. Sortez-la 10 min avant : au sortir du frigo, la feta n’a aucun goût.',
    ingredients: [
      { nom: 'Lentilles vertes', quantite: '150 g cuites', rayon: 'Épicerie' },
      { nom: 'Feta', quantite: '40 g', rayon: 'Crèmerie' },
      { nom: 'Tomates', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignon', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Persil', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Coupez les tomates en dés et l’oignon très finement.',
      'Mélangez aux lentilles froides avec l’huile.',
      'Émiettez la feta par-dessus et ajoutez le persil au dernier moment.',
    ],
    astuce: 'Se transporte parfaitement et se mange froide : c’est le déjeuner de bureau type.',
    conservation: '3 jours au frais',
    saisons: ['ete', 'automne'],
  },
  {
    id: 'steak-patate-douce',
    titre: 'Steak haché, patate douce et brocolis',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 475,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Steak haché 5 %', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Patate douce', quantite: '1 moyenne', rayon: 'Fruits et légumes' },
      { nom: 'Brocolis', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez la patate douce en morceaux à la vapeur, 15 minutes, puis écrasez-la à la fourchette.',
      'Faites cuire les brocolis 8 minutes dans le même panier.',
      'Saisissez le steak 2 minutes par face.',
      'Assaisonnez l’écrasé de muscade et d’huile.',
    ],
    astuce:
      'Le steak à 5 % de matière grasse apporte autant de protéines qu’un 15 %, pour 70 kcal de moins.',
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'blanquette-express-dinde',
    titre: 'Blanquette express de dinde et riz',
    moment: 'dejeuner',
    minutes: 30,
    kcal: 480,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole', 'batch'],
    cuisine: 'francaise',
    regimes: ['sans-gluten'],
    rechauffage: 'À feu doux sans faire bouillir : la crème légère tranche à l’ébullition.',
    ingredients: [
      { nom: 'Escalope de dinde', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Riz basmati', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Carotte', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Champignons de Paris', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Crème légère', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Thym', quantite: '1 branche', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites dorer la dinde en morceaux 5 minutes.',
      'Ajoutez carottes en rondelles, champignons, thym et un demi-verre d’eau.',
      'Couvrez et laissez mijoter 15 minutes.',
      'Ajoutez la crème hors du feu et servez sur le riz.',
    ],
    astuce: 'La crème hors du feu ne tranche pas et il en faut deux fois moins pour le même goût.',
    conservation: '2 jours au frais',
  },
  {
    id: 'dinde-ratatouille',
    titre: 'Escalope de dinde, ratatouille et semoule',
    moment: 'dejeuner',
    minutes: 40,
    kcal: 460,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['batch', 'economique'],
    cuisine: 'mediterraneenne',
    regimes: ['sans-lactose'],
    rechauffage: 'La ratatouille est meilleure réchauffée, 5 min à la poêle. La dinde, elle, se réchauffe 1 min à peine.',
    ingredients: [
      { nom: 'Escalope de dinde', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Semoule', quantite: '50 g crue', rayon: 'Épicerie' },
      { nom: 'Aubergine', quantite: '1 petite', rayon: 'Fruits et légumes' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Coupez les légumes en dés et faites-les mijoter 30 minutes à couvert.',
      'Poêlez l’escalope 5 minutes par face.',
      'Versez l’eau bouillante sur la semoule, couvrez 5 minutes, égrainez.',
      'Servez la ratatouille sur la semoule, l’escalope à côté.',
    ],
    astuce: 'La ratatouille se fait en grande quantité et se garde 4 jours au frais.',
    conservation: '4 jours au réfrigérateur',
    saisons: ['ete'],
  },
  {
    id: 'lentilles-oeufs',
    titre: 'Lentilles, œufs durs et carottes râpées',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 440,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique', 'nomade'],
    cuisine: 'francaise',
    regimes: ['sans-gluten'],
    rechauffage: 'Se mange froid ou tiède. Ne réchauffez pas les œufs durs, ils deviennent caoutchouteux.',
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Lentilles vertes', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Échalote', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Moutarde', quantite: '1 cc', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez les lentilles 20 minutes dans l’eau non salée.',
      'Faites durcir les œufs 9 minutes.',
      'Râpez les carottes, assaisonnez avec l’huile et la moutarde.',
      'Servez les lentilles tièdes avec l’échalote émincée et les œufs coupés en deux.',
    ],
    astuce: 'Saler les lentilles en début de cuisson durcit leur peau — attendez la fin.',
    conservation: '3 jours au réfrigérateur',
  },
  {
    id: 'salade-pois-chiches',
    titre: 'Salade de pois chiches, feta et concombre',
    moment: 'dejeuner',
    minutes: 10,
    kcal: 450,
    couvre: ['proteine', 'feculent', 'legume', 'laitier', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson', 'nomade'],
    cuisine: 'orientale',
    regimes: ['sans-gluten'],
    ingredients: [
      { nom: 'Pois chiches cuits', quantite: '150 g égouttés', rayon: 'Épicerie' },
      { nom: 'Feta', quantite: '40 g', rayon: 'Crèmerie' },
      { nom: 'Concombre', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Tomates cerises', quantite: '8', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Menthe fraîche', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Rincez les pois chiches à l’eau froide et égouttez-les bien.',
      'Coupez le concombre en dés et les tomates en deux.',
      'Mélangez le tout avec l’huile, le jus de citron et la menthe ciselée.',
      'Émiettez la feta par-dessus au moment de servir.',
    ],
    astuce: 'Elle se transporte sans dommage : la feta empêche la salade de rendre son eau.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'quinoa-saumon-fume',
    titre: 'Quinoa au saumon fumé et petits pois',
    moment: 'dejeuner',
    minutes: 20,
    kcal: 465,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['nomade', 'batch'],
    cuisine: 'nordique',
    regimes: ['sans-gluten', 'sans-lactose'],
    rechauffage: 'Se mange froid. Le saumon fumé ne se réchauffe pas.',
    ingredients: [
      { nom: 'Quinoa', quantite: '60 g cru', rayon: 'Épicerie' },
      { nom: 'Saumon fumé', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Petits pois', quantite: '150 g', rayon: 'Surgelés' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Aneth', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Cuisez le quinoa 15 minutes dans deux fois son volume d’eau.',
      'Ajoutez les petits pois les 5 dernières minutes, directement dans la casserole.',
      'Égouttez, laissez tiédir, assaisonnez à l’huile et au citron.',
      'Ajoutez le saumon coupé en lanières et l’aneth.',
    ],
    conservation: '2 jours au réfrigérateur',
  },
]
