import type { Recette } from './types'

/**
 * Le dîner suit la même structure que le déjeuner, en un peu plus léger : la
 * portion de féculents descend, les légumes prennent la place. Quantités pour
 * une personne.
 */
export const DINERS: Recette[] = [
  {
    id: 'cabillaud-papillote',
    titre: 'Cabillaud en papillote, riz et courgettes',
    moment: 'diner',
    minutes: 30,
    kcal: 430,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    regimes: ['sans-gluten', 'sans-lactose'],
    appareils: [
      {
        appareil: 'Air fryer',
        instructions: 'Papillote fermée, 15 min à 180 °C. Le papier ne doit pas toucher la résistance.',
      },
      {
        appareil: 'Four',
        instructions: '20 min à 200 °C, papillote posée sur une plaque froide.',
      },
    ],
    ingredients: [
      { nom: 'Dos de cabillaud', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Riz basmati', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: '1 moyenne', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Thym', quantite: '1 branche', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Préchauffez le four à 200 °C.',
      'Coupez la courgette en rondelles fines et déposez-les sur une feuille de papier cuisson.',
      'Posez le cabillaud dessus, arrosez d’huile, ajoutez le citron en rondelles et le thym.',
      'Fermez la papillote hermétiquement et enfournez 18 minutes.',
      'Faites cuire le riz pendant ce temps.',
    ],
    astuce: 'La papillote se prépare le matin et attend au frais toute la journée.',
  },
  {
    id: 'omelette-champignons',
    titre: 'Omelette aux champignons et salade',
    moment: 'diner',
    minutes: 15,
    kcal: 390,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'economique'],
    cuisine: 'francaise',
    regimes: ['sans-lactose'],
    substitutions: [
      {
        ingredient: 'Champignons de Paris',
        par: 'poêlée de champignons surgelée',
        effet: 'aucun épluchage, égouttez bien avant de saler',
      },
    ],
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Champignons de Paris', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Persil', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites revenir les champignons émincés à sec jusqu’à évaporation de leur eau.',
      'Battez les œufs, salez, poivrez, versez sur les champignons.',
      'Laissez prendre à feu doux 4 minutes, pliez en deux.',
      'Servez avec la salade assaisonnée à l’huile d’olive et le pain.',
    ],
    astuce:
      'Cuire les champignons à sec avant d’huiler évite qu’ils boivent toute la matière grasse.',
    saisons: ['automne'],
  },
  {
    id: 'saumon-brocolis',
    titre: 'Saumon vapeur, écrasé de pommes de terre et brocolis',
    moment: 'diner',
    minutes: 30,
    kcal: 510,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole', 'plaisir'],
    cuisine: 'nordique',
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Pavé de saumon', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '2 moyennes', rayon: 'Fruits et légumes' },
      { nom: 'Brocolis', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Cuisez pommes de terre et brocolis à la vapeur, 20 minutes.',
      'Ajoutez le saumon dans le panier vapeur les 10 dernières minutes.',
      'Écrasez les pommes de terre à la fourchette avec l’huile d’olive.',
      'Servez avec un filet de citron.',
    ],
  },
  {
    id: 'soupe-legumes-lentilles',
    titre: 'Soupe épaisse de légumes aux lentilles primaire',
    moment: 'diner',
    minutes: 30,
    kcal: 375,
    couvre: ['legume', 'proteine', 'feculent', 'matiere-grasse'],
    tags: ['batch', 'vegetarien', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    regimes: ['vegan', 'sans-gluten', 'sans-lactose'],
    rechauffage: 'À la casserole, jamais au micro-ondes en une fois : le centre reste froid. Congelée, décongélation la veille au réfrigérateur.',
    appareils: [
      {
        appareil: 'Autocuiseur',
        instructions: '8 min sous pression après le sifflement, puis mixez. Les lentilles primaire n’ont pas besoin de plus.',
      },
    ],
    ingredients: [
      { nom: 'Lentilles primaire', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Poireau', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Pomme de terre', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Cumin', quantite: '1 cc', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émincez les légumes et faites-les suer 5 minutes dans l’huile.',
      'Ajoutez les lentilles, le cumin et 800 ml d’eau.',
      'Laissez cuire 20 minutes à petits bouillons.',
      'Mixez à peine — la soupe doit rester épaisse pour tenir au corps.',
    ],
    astuce: 'Les lentilles primaire se délitent en cuisant : c’est elles qui épaississent la soupe.',
    conservation: '4 jours au réfrigérateur, 3 mois au congélateur',
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'gratin-courgettes-jambon',
    titre: 'Gratin de courgettes au jambon',
    moment: 'diner',
    minutes: 40,
    kcal: 420,
    couvre: ['proteine', 'legume', 'laitier', 'matiere-grasse'],
    tags: ['batch', 'plaisir'],
    cuisine: 'francaise',
    regimes: ['sans-gluten'],
    rechauffage: '15 min à 180 °C au four, à couvert. Au micro-ondes le gratin rend son eau et le dessus ramollit.',
    ingredients: [
      { nom: 'Courgettes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Jambon blanc', quantite: '1 tranche épaisse', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Fromage blanc', quantite: '100 g', rayon: 'Crèmerie' },
      { nom: 'Œuf', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Gruyère râpé', quantite: '20 g', rayon: 'Crèmerie' },
      { nom: 'Muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir les courgettes en rondelles 10 minutes, sans matière grasse.',
      'Battez l’œuf avec le fromage blanc et la muscade.',
      'Mélangez avec les courgettes et le jambon en dés, versez dans un plat.',
      'Parsemez de gruyère et enfournez 20 minutes à 200 °C.',
    ],
    astuce:
      'Le fromage blanc remplace la crème sans qu’on le remarque, à condition de ne pas le faire bouillir.',
    conservation: '3 jours au réfrigérateur',
    saisons: ['ete', 'automne'],
  },
  {
    id: 'soupe-courge-lentilles',
    titre: 'Soupe de courge et lentilles primaire',
    moment: 'diner',
    minutes: 30,
    kcal: 400,
    couvre: ['proteine', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique', 'une-casserole'],
    cuisine: 'orientale',
    regimes: ['vegan', 'sans-lactose'],
    rechauffage: 'À la casserole à feu doux, en remuant : la courge attache vite.',
    ingredients: [
      { nom: 'Courge butternut', quantite: '400 g', rayon: 'Fruits et légumes' },
      { nom: 'Lentilles primaire', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Oignon', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 cc', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Pain complet', quantite: '1 tranche', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Faites revenir l’oignon et le cumin 5 minutes.',
      'Ajoutez la courge en cubes, les lentilles et de l’eau à hauteur.',
      'Laissez cuire 20 minutes, puis mixez.',
      'Servez avec la tranche de pain grillée.',
    ],
    astuce: 'Les lentilles primaire épaississent la soupe : plus besoin de crème pour qu’elle tienne.',
    conservation: '4 jours au frais',
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'crevettes-boulgour',
    titre: 'Poêlée de crevettes, courgettes et boulgour',
    moment: 'diner',
    minutes: 20,
    kcal: 440,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['rapide', 'une-casserole'],
    cuisine: 'mediterraneenne',
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Crevettes décortiquées', quantite: '150 g', rayon: 'Surgelés' },
      { nom: 'Boulgour', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: '1 moyenne', rayon: 'Fruits et légumes' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites gonfler le boulgour 12 minutes dans deux fois son volume d’eau bouillante.',
      'Faites sauter la courgette en demi-rondelles avec l’ail, 8 minutes.',
      'Ajoutez les crevettes 3 minutes, pas davantage : au-delà elles durcissent.',
      'Mélangez au boulgour, terminez au citron.',
    ],
    astuce: 'Les crevettes surgelées cuisent sans décongélation et coûtent moitié moins cher.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'oeufs-cocotte-epinards',
    titre: 'Œufs cocotte aux épinards',
    moment: 'diner',
    minutes: 20,
    kcal: 420,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'economique'],
    cuisine: 'francaise',
    substitutions: [
      {
        ingredient: 'Crème légère',
        par: 'fromage blanc',
        effet: 'plus acide, 30 kcal de moins',
      },
    ],
    appareils: [
      {
        appareil: 'Micro-ondes',
        instructions: 'Ramequin couvert, 1 min 30 à 700 W. Percez le jaune avant, sinon il éclate.',
      },
    ],
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Épinards', quantite: '200 g', rayon: 'Surgelés' },
      { nom: 'Crème légère', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Pain complet', quantite: '1 tranche épaisse', rayon: 'Boulangerie' },
      { nom: 'Muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir les épinards jusqu’à évaporation de l’eau.',
      'Répartissez-les dans deux ramequins, creusez un puits, cassez-y un œuf.',
      'Ajoutez une cuillère de crème et enfournez 12 minutes à 180 °C.',
      'Le blanc doit être pris et le jaune encore coulant. Servez avec le pain.',
    ],
    astuce: 'Sortez-les quand le blanc tremble encore un peu : la cuisson finit dans le ramequin.',
  },
  {
    id: 'merlan-celeri',
    titre: 'Merlan, écrasé de céleri et carottes',
    moment: 'diner',
    minutes: 30,
    kcal: 430,
    couvre: ['proteine', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Filet de merlan', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Céleri-rave', quantite: '300 g', rayon: 'Fruits et légumes' },
      { nom: 'Carotte', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Persil', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Cuisez céleri et carottes en cubes à la vapeur, 20 minutes.',
      'Écrasez-les à la fourchette avec l’huile — un mixeur en ferait une colle.',
      'Faites cuire le merlan 8 minutes au-dessus, dans le même panier.',
      'Servez parsemé de persil.',
    ],
    astuce: 'Le céleri-rave fait un écrasé à moitié moins de calories que la pomme de terre.',
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'gratin-chou-fleur',
    titre: 'Gratin de chou-fleur au jambon',
    moment: 'diner',
    minutes: 40,
    kcal: 450,
    couvre: ['proteine', 'legume', 'laitier'],
    tags: ['batch', 'economique'],
    cuisine: 'francaise',
    regimes: ['sans-gluten'],
    rechauffage: '15 min à 180 °C, à couvert.',
    ingredients: [
      { nom: 'Chou-fleur', quantite: '500 g', rayon: 'Fruits et légumes' },
      { nom: 'Jambon blanc découenné', quantite: '2 tranches', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Fromage blanc 3 %', quantite: '150 g', rayon: 'Crèmerie' },
      { nom: 'Gruyère râpé', quantite: '30 g', rayon: 'Crèmerie' },
      { nom: 'Muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez le chou-fleur en bouquets 12 minutes à la vapeur.',
      'Mélangez le fromage blanc, la muscade et le jambon coupé en lanières.',
      'Versez sur le chou-fleur dans un plat, couvrez de gruyère.',
      'Enfournez 20 minutes à 200 °C.',
    ],
    astuce: 'Ne faites jamais bouillir le fromage blanc : il tranche. Le four suffit à le lier.',
    conservation: '3 jours au frais',
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'salade-tiede-maquereau',
    titre: 'Salade tiède de pommes de terre et maquereau',
    moment: 'diner',
    minutes: 25,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['economique', 'nomade'],
    cuisine: 'nordique',
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Filets de maquereau', quantite: '1 boîte', rayon: 'Épicerie' },
      { nom: 'Pommes de terre', quantite: '2 moyennes', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
      { nom: 'Échalote', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Moutarde', quantite: '1 cc', rayon: 'Épicerie' },
      { nom: 'Vinaigre blanc', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez les pommes de terre en robe des champs, 20 minutes.',
      'Coupez-les tièdes en rondelles : c’est tiède qu’elles boivent l’assaisonnement.',
      'Mélangez moutarde, vinaigre et échalote ciselée, versez dessus.',
      'Ajoutez le maquereau émietté et la salade.',
    ],
    astuce: 'Le maquereau en boîte est le poisson gras le moins cher, et le plus riche en oméga-3.',
  },
  {
    id: 'tofu-brocolis-nouilles',
    titre: 'Tofu sauté, brocolis et nouilles',
    moment: 'diner',
    minutes: 20,
    kcal: 460,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien', 'une-casserole'],
    cuisine: 'asiatique',
    regimes: ['vegan', 'sans-lactose'],
    substitutions: [
      {
        ingredient: 'Sauce soja',
        par: 'tamari',
        effet: 'sans gluten, goût plus rond',
      },
    ],
    appareils: [
      {
        appareil: 'Wok',
        instructions: 'Tofu d’abord à feu vif sans le remuer 2 min, pour qu’il dore au lieu de s’effriter.',
      },
    ],
    ingredients: [
      { nom: 'Tofu ferme', quantite: '150 g', rayon: 'Crèmerie' },
      { nom: 'Nouilles complètes', quantite: '50 g crues', rayon: 'Épicerie' },
      { nom: 'Brocolis', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Sauce soja', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Pressez le tofu entre deux feuilles de papier absorbant, 5 minutes.',
      'Coupez-le en cubes et faites-le dorer à feu vif sans le retourner trop tôt.',
      'Ajoutez les brocolis et l’ail, 6 minutes, puis la sauce soja.',
      'Mélangez aux nouilles cuites.',
    ],
    astuce: 'Le tofu ne dore que s’il est sec : c’est l’essorage qui fait toute la différence.',
  },
  {
    id: 'chili-vegetarien',
    titre: 'Chili végétarien aux haricots rouges',
    moment: 'diner',
    minutes: 35,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique', 'une-casserole'],
    cuisine: 'mexicaine',
    regimes: ['vegan', 'sans-gluten', 'sans-lactose'],
    rechauffage: 'Meilleur le lendemain. À la casserole avec un fond d’eau, 5 min.',
    appareils: [
      {
        appareil: 'Cocotte-minute',
        instructions: '10 min sous pression au lieu de 35, les haricots étant déjà cuits.',
      },
    ],
    ingredients: [
      { nom: 'Haricots rouges cuits', quantite: '200 g égouttés', rayon: 'Épicerie' },
      { nom: 'Tomates concassées', quantite: '200 g', rayon: 'Épicerie' },
      { nom: 'Riz basmati', quantite: '40 g cru', rayon: 'Épicerie' },
      { nom: 'Poivrons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Oignon', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 cc', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir oignon et poivron en dés avec le cumin, 8 minutes.',
      'Ajoutez tomates et haricots, laissez mijoter 20 minutes à couvert.',
      'Servez sur le riz.',
    ],
    astuce: 'Il est franchement meilleur le lendemain : c’est le plat à faire le dimanche soir.',
    conservation: '4 jours au frais',
  },
  {
    id: 'papillote-dinde-poireaux',
    titre: 'Papillote de dinde aux poireaux',
    moment: 'diner',
    minutes: 30,
    kcal: 440,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Escalope de dinde', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poireau', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Riz basmati', quantite: '45 g cru', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Thym', quantite: '1 branche', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Émincez les poireaux, disposez-les au fond du papier cuisson.',
      'Posez la dinde dessus avec le citron en rondelles, le thym et l’huile.',
      'Fermez hermétiquement et enfournez 25 minutes à 200 °C.',
      'Servez avec le riz et le jus de la papillote.',
    ],
    astuce: 'La papillote cuit à la vapeur du légume : rien n’attache et il n’y a pas de plat à laver.',
    saisons: ['automne', 'hiver'],
  },
]
