import type { Recette } from './types'

/**
 * Le petit déjeuner de l'ordonnance : un féculent, une matière grasse, un
 * produit laitier, un fruit, une boisson non sucrée. Chaque recette d'ici
 * respecte cette structure — elle en change seulement l'habillage.
 */
export const PETITS_DEJEUNERS: Recette[] = [
  {
    id: 'pdj-porridge',
    titre: 'Porridge aux flocons et fruits frais',
    moment: 'petit-dejeuner',
    minutes: 10,
    kcal: 330,
    couvre: ['feculent', 'laitier', 'fruit'],
    tags: ['rapide', 'vegetarien', 'economique'],
    cuisine: 'britannique',
    substitutions: [
      {
        ingredient: 'Lait demi-écrémé',
        par: 'boisson d’avoine ou de soja',
        effet: 'sans lactose, un peu plus sucré',
      },
    ],
    appareils: [
      {
        appareil: 'Micro-ondes',
        instructions: 'Flocons et lait dans un grand bol, 2 min à 900 W, remuez à mi-cuisson pour éviter le débordement.',
      },
    ],
    ingredients: [
      { nom: 'Flocons d’avoine', quantite: '40 g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '200 ml', rayon: 'Crèmerie' },
      { nom: 'Fruit de saison', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cannelle', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites chauffer le lait avec les flocons, 5 minutes à feu doux en remuant.',
      'Versez dans un bol, ajoutez le fruit coupé et la cannelle.',
    ],
    astuce: 'La cannelle sucre sans sucre — elle suffit à se passer de miel.',
  },
  {
    id: 'pdj-tartines-beurre',
    titre: 'Tartines beurrées, fromage blanc et fruit',
    moment: 'petit-dejeuner',
    minutes: 5,
    kcal: 330,
    couvre: ['feculent', 'matiere-grasse', 'laitier', 'fruit'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson', 'economique'],
    cuisine: 'francaise',
    ingredients: [
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches (50 g)', rayon: 'Boulangerie' },
      { nom: 'Beurre à 60 %', quantite: 'une fine couche', rayon: 'Crèmerie' },
      { nom: 'Fromage blanc', quantite: '100 g', rayon: 'Crèmerie' },
      { nom: 'Fruit de saison', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Beurrez les tartines finement — le beurre doit se voir, pas s’empiler.',
      'Servez le fromage blanc à côté, avec le fruit coupé dedans.',
    ],
    astuce: 'C’est le petit déjeuner de référence de l’ordonnance. Les autres n’en sont que des variantes.',
  },
  {
    id: 'pdj-oeufs-brouilles',
    titre: 'Œufs brouillés et tartines',
    moment: 'petit-dejeuner',
    minutes: 10,
    kcal: 375,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['rapide', 'vegetarien'],
    cuisine: 'francaise',
    substitutions: [
      {
        ingredient: 'Ciboulette',
        par: 'persil ou aneth',
        effet: 'plus anisé avec l’aneth',
      },
    ],
    appareils: [
      {
        appareil: 'Micro-ondes',
        instructions: 'Œufs battus dans un bol beurré, 40 s à 700 W, fouettez, puis 20 s de plus. Ils finissent de prendre hors du four.',
      },
    ],
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Beurre à 60 %', quantite: '1 noisette', rayon: 'Crèmerie' },
      { nom: 'Ciboulette', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Battez les œufs à la fourchette, salez, poivrez.',
      'Versez dans une poêle beurrée à feu très doux, remuez sans arrêt 3 minutes.',
      'Retirez du feu quand ils sont encore crémeux — ils finissent de cuire seuls.',
      'Parsemez de ciboulette et servez avec les tartines.',
    ],
    astuce: 'C’est la variante écrite noir sur blanc sur l’ordonnance. Le feu doux fait toute la différence.',
  },
  {
    id: 'pdj-bol-fromage-blanc',
    titre: 'Bol de fromage blanc, muesli et fruits rouges',
    moment: 'petit-dejeuner',
    minutes: 5,
    kcal: 335,
    couvre: ['laitier', 'feculent', 'fruit'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson'],
    cuisine: 'nordique',
    ingredients: [
      { nom: 'Fromage blanc 3 %', quantite: '150 g', rayon: 'Crèmerie' },
      { nom: 'Muesli sans sucre ajouté', quantite: '40 g', rayon: 'Épicerie' },
      { nom: 'Fruits rouges', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Cannelle', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Versez le fromage blanc dans un bol.',
      'Ajoutez le muesli, les fruits rouges et la cannelle.',
    ],
    astuce: 'Hors saison, les fruits rouges surgelés font l’affaire : sortis la veille au frigo, ils rendent un jus qui parfume tout le bol.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'pdj-pain-perdu',
    titre: 'Pain perdu au lait, sans sucre ajouté',
    moment: 'petit-dejeuner',
    minutes: 12,
    kcal: 345,
    couvre: ['feculent', 'laitier', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'economique'],
    cuisine: 'francaise',
    substitutions: [
      {
        ingredient: 'Pain spécial rassis',
        par: 'brioche rassise',
        effet: 'plus riche, comptez 60 kcal de plus',
      },
    ],
    ingredients: [
      { nom: 'Pain spécial rassis', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Lait demi-écrémé', quantite: '100 ml', rayon: 'Crèmerie' },
      { nom: 'Œuf', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Beurre à 60 %', quantite: '1 noisette', rayon: 'Crèmerie' },
      { nom: 'Vanille en poudre', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Battez l’œuf avec le lait et la vanille.',
      'Trempez les tranches 1 minute par face.',
      'Dorez à la poêle beurrée, 2 minutes par face.',
    ],
    astuce: 'La vanille et la cannelle donnent l’impression du sucré. Le pain rassis boit mieux que le pain frais — c’est la recette anti-gaspillage du dimanche.',
  },
  {
    id: 'pdj-overnight-oats',
    titre: 'Flocons trempés de la nuit, pomme et cannelle',
    moment: 'petit-dejeuner',
    minutes: 5,
    kcal: 325,
    couvre: ['feculent', 'laitier', 'fruit'],
    tags: ['rapide', 'batch', 'vegetarien', 'sans-cuisson', 'nomade'],
    cuisine: 'americaine',
    substitutions: [
      {
        ingredient: 'Yaourt nature',
        par: 'yaourt de soja',
        effet: 'sans lactose, texture plus fluide',
      },
    ],
    rechauffage: 'Se mange froid, sorti du réfrigérateur. Passé 30 s au micro-ondes il redevient un porridge tiède.',
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Flocons d’avoine', quantite: '40 g', rayon: 'Épicerie' },
      { nom: 'Yaourt nature', quantite: '1 pot', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: '80 ml', rayon: 'Crèmerie' },
      { nom: 'Pomme', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cannelle', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'La veille au soir, mélangez flocons, yaourt et lait dans un bocal.',
      'Ajoutez la moitié de la pomme râpée et la cannelle, fermez, au frigo.',
      'Au matin, complétez avec le reste de la pomme coupée en dés.',
    ],
    astuce: 'Préparez trois bocaux d’un coup le dimanche soir : les matins pressés sont réglés jusqu’à mercredi.',
  },
  {
    id: 'pdj-smoothie-bowl',
    titre: 'Bol smoothie banane-fraise et flocons',
    moment: 'petit-dejeuner',
    minutes: 8,
    kcal: 330,
    couvre: ['fruit', 'laitier', 'feculent'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson'],
    cuisine: 'americaine',
    substitutions: [
      {
        ingredient: 'Fraises',
        par: 'fruits rouges surgelés',
        effet: 'plus épais et glacé, disponible toute l’année',
      },
    ],
    appareils: [
      {
        appareil: 'Blender',
        instructions: 'Tout ensemble 30 s. Sans blender, écrasez la banane à la fourchette et coupez les fraises : la texture est plus rustique, le goût identique.',
      },
    ],
    ingredients: [
      { nom: 'Banane', quantite: '1 petite', rayon: 'Fruits et légumes' },
      { nom: 'Fraises', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Yaourt nature', quantite: '1 pot', rayon: 'Crèmerie' },
      { nom: 'Flocons d’avoine', quantite: '30 g', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mixez la banane, la moitié des fraises et le yaourt.',
      'Versez dans un bol, parsemez de flocons et du reste de fraises coupées.',
    ],
    astuce: 'Congelez la banane coupée la veille : le smoothie devient épais comme une glace, sans rien ajouter.',
    saisons: ['printemps', 'ete'],
  },
  {
    id: 'pdj-tartine-avocat',
    titre: 'Tartine d’avocat et œuf poché',
    moment: 'petit-dejeuner',
    minutes: 12,
    kcal: 380,
    couvre: ['feculent', 'matiere-grasse', 'proteine', 'legume'],
    tags: ['vegetarien'],
    cuisine: 'americaine',
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Avocat', quantite: '½', rayon: 'Fruits et légumes' },
      { nom: 'Œuf', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Citron', quantite: '¼', rayon: 'Fruits et légumes' },
      { nom: 'Vinaigre blanc', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Portez une casserole d’eau à frémissement avec le vinaigre.',
      'Cassez l’œuf dans un bol, glissez-le dans l’eau tournante, 3 minutes.',
      'Écrasez l’avocat au citron, sel, poivre, étalez sur les tartines.',
      'Posez l’œuf poché dessus.',
    ],
    astuce: 'L’avocat compte comme la matière grasse du repas : pas de beurre en plus.',
  },
  {
    id: 'pdj-yaourt-grec-noix',
    titre: 'Yaourt à la grecque, poire et noix',
    moment: 'petit-dejeuner',
    minutes: 5,
    kcal: 340,
    couvre: ['laitier', 'fruit', 'matiere-grasse', 'feculent'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson'],
    cuisine: 'mediterraneenne',
    ingredients: [
      { nom: 'Yaourt à la grecque', quantite: '1 pot', rayon: 'Crèmerie' },
      { nom: 'Poire', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cerneaux de noix', quantite: '3', rayon: 'Épicerie' },
      { nom: 'Pain spécial de boulangerie', quantite: '1 tranche', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Coupez la poire en dés, mélangez au yaourt.',
      'Concassez les noix par-dessus.',
      'Servez avec la tranche de pain.',
    ],
    saisons: ['automne', 'hiver'],
  },
  {
    id: 'pdj-crepes-avoine',
    titre: 'Crêpes d’avoine au yaourt',
    moment: 'petit-dejeuner',
    minutes: 15,
    kcal: 340,
    couvre: ['feculent', 'laitier', 'proteine', 'fruit'],
    tags: ['batch', 'vegetarien', 'economique'],
    cuisine: 'francaise',
    rechauffage: 'À la poêle sèche, 1 min par face. Au micro-ondes elles ramollissent.',
    appareils: [
      {
        appareil: 'Crêpière électrique',
        instructions: 'Deux crêpes à la fois, 2 min par face à feu moyen. La pâte d’avoine dore plus vite que la pâte à froment.',
      },
    ],
    conservation: '2 jours au réfrigérateur, se réchauffent à la poêle',
    ingredients: [
      { nom: 'Flocons d’avoine', quantite: '40 g', rayon: 'Épicerie' },
      { nom: 'Œuf', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Yaourt nature', quantite: '½ pot', rayon: 'Crèmerie' },
      { nom: 'Levure chimique', quantite: '½ cc', rayon: 'Épicerie' },
      { nom: 'Compote sans sucre ajouté', quantite: '1 pot', rayon: 'Épicerie' },
    ],
    etapes: [
      'Mixez les flocons en poudre grossière.',
      'Mélangez avec l’œuf, le yaourt et la levure, laissez reposer 5 minutes.',
      'Faites cuire trois petites crêpes épaisses à la poêle antiadhésive, 2 minutes par face.',
      'Servez avec la compote.',
    ],
    astuce: 'Doublez les proportions le week-end : les crêpes se réchauffent en 30 secondes à la poêle en semaine.',
  },
  {
    id: 'pdj-riz-au-lait',
    titre: 'Riz au lait à la cannelle, sans sucre',
    moment: 'petit-dejeuner',
    minutes: 30,
    kcal: 335,
    couvre: ['feculent', 'laitier', 'fruit'],
    tags: ['batch', 'vegetarien', 'economique', 'une-casserole'],
    cuisine: 'francaise',
    difficulte: 'facile',
    regimes: ['sans-gluten'],
    rechauffage: 'Une cuillère de lait froid dans le bol, puis 1 min au micro-ondes : sans le lait il devient compact.',
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Riz rond', quantite: '40 g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '250 ml', rayon: 'Crèmerie' },
      { nom: 'Bâton de cannelle', quantite: '1', rayon: 'Épicerie' },
      { nom: 'Raisins secs', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Portez le lait à frémissement avec la cannelle.',
      'Versez le riz, laissez cuire 25 minutes à feu très doux en remuant souvent.',
      'Ajoutez les raisins secs en fin de cuisson, retirez le bâton de cannelle.',
    ],
    astuce: 'Les raisins secs apportent tout le sucré nécessaire en gonflant dans le lait.',
  },
  {
    id: 'pdj-tartine-ricotta-figue',
    titre: 'Tartine ricotta et figue fraîche',
    moment: 'petit-dejeuner',
    minutes: 5,
    kcal: 330,
    couvre: ['feculent', 'laitier', 'fruit'],
    tags: ['rapide', 'vegetarien', 'sans-cuisson'],
    cuisine: 'italienne',
    ingredients: [
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Ricotta', quantite: '80 g', rayon: 'Crèmerie' },
      { nom: 'Figues fraîches', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Thym frais', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Étalez la ricotta sur les tartines.',
      'Posez les figues coupées en quartiers, poivrez, ajoutez le thym.',
    ],
    saisons: ['ete', 'automne'],
  },
  {
    id: 'pdj-muesli-maison',
    titre: 'Muesli maison grillé, lait et fruit',
    moment: 'petit-dejeuner',
    minutes: 20,
    kcal: 340,
    couvre: ['feculent', 'laitier', 'fruit', 'matiere-grasse'],
    tags: ['batch', 'vegetarien', 'economique'],
    cuisine: 'nordique',
    rechauffage: 'Rien à réchauffer. S’il a pris l’humidité, 5 min à 150 °C lui rendent son croquant.',
    conservation: '3 semaines dans un bocal hermétique',
    ingredients: [
      { nom: 'Flocons d’avoine', quantite: '250 g (pour le bocal)', rayon: 'Épicerie' },
      { nom: 'Amandes effilées', quantite: '50 g', rayon: 'Épicerie' },
      { nom: 'Graines de courge', quantite: '30 g', rayon: 'Épicerie' },
      { nom: 'Huile de colza', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '200 ml par bol', rayon: 'Crèmerie' },
      { nom: 'Fruit de saison', quantite: '1 par bol', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Mélangez flocons, amandes et graines avec l’huile.',
      'Étalez sur une plaque, enfournez 15 minutes à 160 °C en remuant à mi-cuisson.',
      'Laissez refroidir complètement avant de mettre en bocal.',
      'Au matin, comptez 40 g par bol, avec le lait et le fruit.',
    ],
    astuce: 'Les mueslis du commerce montent souvent à 20 g de sucre pour 100 g. Celui-ci n’en contient aucun.',
  },
  {
    id: 'pdj-galette-sarrasin',
    titre: 'Galette de sarrasin, jambon et fromage blanc',
    moment: 'petit-dejeuner',
    minutes: 10,
    kcal: 355,
    couvre: ['feculent', 'proteine', 'laitier'],
    tags: ['rapide'],
    cuisine: 'francaise',
    ingredients: [
      { nom: 'Galette de sarrasin', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Jambon blanc découenné', quantite: '1 tranche', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Fromage blanc', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Ciboulette', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
      { nom: 'Fruit de saison', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Réchauffez la galette à la poêle sèche, 1 minute par face.',
      'Tartinez de fromage blanc à la ciboulette, ajoutez le jambon, pliez en quatre.',
      'Servez avec le fruit.',
    ],
    astuce: 'Un petit déjeuner salé cale souvent mieux qu’un sucré quand la matinée est longue.',
  },
  {
    id: 'pdj-nomade',
    titre: 'Le petit déjeuner de sac',
    moment: 'petit-dejeuner',
    minutes: 3,
    kcal: 320,
    couvre: ['feculent', 'laitier', 'fruit'],
    tags: ['rapide', 'sans-cuisson', 'nomade', 'economique'],
    cuisine: 'francaise',
    ingredients: [
      { nom: 'Pain spécial de boulangerie', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Portion de fromage', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Fruit qui se transporte (pomme, clémentine)', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Thé ou tisane', quantite: '1 sachet', rayon: 'Épicerie' },
    ],
    etapes: [
      'Emballez le tout la veille au soir dans une boîte.',
      'Sur place, prenez le temps de vous asseoir dix minutes — c’est ça, le repas.',
    ],
    astuce: 'Partir sans rien puis craquer à 11 h coûte plus cher, en calories comme en moral, que ce sac préparé la veille.',
  },
]
