import type { Recette } from '../types'

/**
 * Les grands plats du monde, écrits pour une personne.
 *
 * Ces recettes n'ont **pas de `region`** : le champ décrit un terroir français ou
 * belge, et coller « région : Toscane » à une bolognaise sans avoir la même
 * finesse pour les cinquante autres pays donnerait une carte à moitié renseignée,
 * ce qui est pire qu'une carte vide. C'est `cuisine` qui les situe.
 */
export const TERROIR_MONDE: Recette[] = [
  {
    id: 'chili-con-carne',
    titre: 'Chili con carne',
    moment: 'diner',
    minutes: 70,
    kcal: 590,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'mexicaine',
    gouts: ['releve', 'epice'],
    typePlat: 'mijote',
    occasions: ['semaine', 'reconfort'],
    regimes: ['sans-gluten', 'sans-lactose'],
    conservation: '4 jours au réfrigérateur, 3 mois au congélateur',
    rechauffage: 'À la casserole à feu doux. Meilleur le lendemain, comme tous les plats à épices.',
    substitutions: [
      { ingredient: 'Steak haché', par: 'protéines de soja réhydratées', effet: 'chili végétarien, ajoutez une cuillère de concentré de tomate pour la profondeur' },
    ],
    ingredients: [
      { nom: 'Steak haché 5 %', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Haricots rouges cuits', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Tomates concassées', quantite: '200 g', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Poivron rouge', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Piment en poudre', quantite: '1/2 CàC', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir l’oignon et le poivron en dés, 8 minutes.',
      'Ajoutez la viande et laissez-la colorer en l’écrasant à la cuillère.',
      'Ajoutez cumin et piment et laissez-les chauffer 1 minute à sec : les épices livrent leur parfum au contact du gras chaud, pas dans le liquide.',
      'Versez les tomates, couvrez et laissez mijoter 40 minutes à feu doux.',
      'Ajoutez les haricots pour les 15 dernières minutes, le temps qu’ils prennent le goût sans se défaire.',
      'Servez avec le riz.',
    ],
    astuce: 'Un carré de chocolat noir en fin de cuisson arrondit l’acidité de la tomate sans sucrer. C’est un vieux truc de cuisine tex-mex, et il marche.',
  },
  {
    id: 'lasagnes-bolognaise',
    titre: 'Lasagnes à la bolognaise',
    moment: 'diner',
    minutes: 105,
    kcal: 640,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['batch'],
    cuisine: 'italienne',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    rechauffage: '20 min à 180 °C à couvert.',
    ingredients: [
      { nom: 'Plaques de lasagne', quantite: '4', rayon: 'Épicerie' },
      { nom: 'Steak haché 5 %', quantite: '100 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Tomates concassées', quantite: '200 g', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Lait demi-écrémé', quantite: '20 cl', rayon: 'Crèmerie' },
      { nom: 'Farine', quantite: '15 g', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '15 g', rayon: 'Crèmerie' },
      { nom: 'Parmesan', quantite: '20 g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites revenir carotte et oignon en tout petits dés 10 minutes, ajoutez la viande et laissez colorer.',
      'Versez les tomates et laissez mijoter 45 minutes à feu doux : une bolognaise rapide reste acide.',
      'Préparez la béchamel : roux, puis lait froid d’un coup en fouettant.',
      'Montez en couches — sauce, pâtes, béchamel — en commençant et en finissant par de la sauce, pour que les pâtes ne sèchent jamais au contact du plat.',
      'Parsemez de parmesan et enfournez 35 minutes à 180 °C.',
      'Laissez reposer 10 minutes avant de couper.',
    ],
    astuce: 'Le lait dans la bolognaise n’est pas une erreur de traduction : ajouté en début de cuisson, il attendrit la viande. La béchamel, elle, arrive après.',
  },
  {
    id: 'risotto-milanaise',
    titre: 'Risotto à la milanaise',
    moment: 'diner',
    minutes: 40,
    kcal: 560,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien'],
    cuisine: 'italienne',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['reception'],
    regimes: ['vegetarien', 'sans-gluten'],
    ingredients: [
      { nom: 'Riz arborio', quantite: '70 g cru', rayon: 'Épicerie' },
      { nom: 'Bouillon de légumes', quantite: '50 cl', rayon: 'Épicerie' },
      { nom: 'Vin blanc sec', quantite: '5 cl', rayon: 'Épicerie' },
      { nom: 'Échalotes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Safran', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Parmesan', quantite: '25 g', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '15 g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites nacrer le riz avec l’échalote 2 minutes : les grains doivent devenir translucides sur les bords.',
      'Déglacez au vin blanc et laissez-le absorber entièrement.',
      'Ajoutez le bouillon chaud, une louche à la fois, en remuant et en attendant l’absorption avant la suivante. Un bouillon froid casse la cuisson à chaque ajout.',
      'Comptez 18 minutes. Ajoutez le safran à mi-parcours.',
      'Hors du feu, incorporez beurre froid et parmesan en remuant vivement — c’est cette étape qui rend le risotto crémeux, pas la crème.',
    ],
    astuce: 'Le risotto se sert « all’onda » : il doit onduler quand on secoue l’assiette. S’il tient en tas, il est trop cuit.',
  },
  {
    id: 'osso-buco',
    titre: 'Osso-buco à la milanaise',
    moment: 'diner',
    minutes: 130,
    kcal: 620,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'italienne',
    gouts: ['acidule', 'herbace'],
    typePlat: 'mijote',
    occasions: ['dimanche'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Jarret de veau', quantite: '1 tranche', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Céleri branche', quantite: '1 branche', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc sec', quantite: '10 cl', rayon: 'Épicerie' },
      { nom: 'Tomates concassées', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Persil plat', quantite: '1 petit bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Polenta', quantite: '50 g crue', rayon: 'Épicerie' },
    ],
    etapes: [
      'Entaillez la membrane du jarret en trois endroits, sinon la tranche se recroqueville à la cuisson.',
      'Farinez légèrement et faites colorer sur les deux faces.',
      'Ajoutez les légumes en dés, déglacez au vin blanc, puis versez les tomates.',
      'Couvrez et laissez mijoter 1 h 45 à feu doux, en retournant à mi-cuisson.',
      'Préparez la gremolata : zeste de citron, persil et ail hachés ensemble, à cru.',
      'Parsemez au moment de servir, avec la polenta.',
    ],
    astuce: 'La gremolata est ce qui empêche l’osso-buco d’être lourd. Elle se fait à la dernière minute et ne cuit jamais.',
  },
  {
    id: 'aubergines-parmigiana',
    titre: 'Aubergines à la parmigiana',
    moment: 'diner',
    minutes: 80,
    kcal: 480,
    couvre: ['legume', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'batch'],
    cuisine: 'italienne',
    gouts: ['doux', 'herbace'],
    typePlat: 'gratin',
    occasions: ['dimanche', 'reception'],
    regimes: ['vegetarien', 'sans-gluten'],
    saisons: ['ete'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Aubergines', quantite: '1 grosse', rayon: 'Fruits et légumes' },
      { nom: 'Tomates concassées', quantite: '200 g', rayon: 'Épicerie' },
      { nom: 'Mozzarella', quantite: '60 g', rayon: 'Crèmerie' },
      { nom: 'Parmesan', quantite: '20 g', rayon: 'Crèmerie' },
      { nom: 'Basilic', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '2 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Coupez les aubergines en tranches, salez-les et laissez dégorger 30 minutes, puis épongez.',
      'Faites-les griller au four à 220 °C, 15 minutes, plutôt que frire : elles boivent trois fois moins d’huile.',
      'Faites réduire les tomates 20 minutes avec le basilic.',
      'Alternez aubergines, sauce et mozzarella égouttée dans un plat, en trois couches.',
      'Terminez par le parmesan et enfournez 30 minutes à 180 °C.',
    ],
    astuce: 'Égouttez la mozzarella une heure à l’avance. Sinon elle rend son eau dans le plat et le gratin nage.',
  },
  {
    id: 'paella-valenciana',
    titre: 'Paella',
    moment: 'diner',
    minutes: 60,
    kcal: 620,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['une-casserole'],
    cuisine: 'mediterraneenne',
    gouts: ['epice'],
    typePlat: 'poelee',
    occasions: ['reception', 'dimanche'],
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Riz rond', quantite: '80 g cru', rayon: 'Épicerie' },
      { nom: 'Cuisse de poulet', quantite: '1/2', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Gambas', quantite: '4', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Moules', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poivron rouge', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Petits pois', quantite: '50 g', rayon: 'Surgelés' },
      { nom: 'Safran', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Bouillon', quantite: '25 cl', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites colorer le poulet dans la poêle, puis le poivron.',
      'Ajoutez le riz et faites-le nacrer 2 minutes.',
      'Versez le bouillon chaud safrané et ne remuez plus jamais : c’est ce qui permet au socarrat, la croûte du fond, de se former.',
      'Laissez cuire 15 minutes à feu moyen, puis disposez gambas, moules et petits pois en surface.',
      'Poursuivez 5 minutes, puis coupez le feu et laissez reposer 5 minutes sous un torchon.',
    ],
    astuce: 'Le socarrat au fond n’est pas du riz brûlé, c’est la partie que les Valenciens se disputent. Écoutez : il doit crépiter en fin de cuisson.',
  },
  {
    id: 'tortilla-patatas',
    titre: 'Tortilla de pommes de terre',
    moment: 'dejeuner',
    minutes: 45,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'nomade', 'economique'],
    cuisine: 'mediterraneenne',
    gouts: ['doux'],
    typePlat: 'poelee',
    occasions: ['pique-nique', 'semaine'],
    regimes: ['vegetarien', 'sans-gluten', 'sans-lactose'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Pommes de terre', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Œufs', quantite: '3', rayon: 'Crèmerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '2 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Coupez les pommes de terre en fines lamelles et faites-les confire à l’huile à feu doux, 20 minutes, avec l’oignon. Elles doivent fondre, jamais frire.',
      'Égouttez-les et mélangez-les aux œufs battus. Laissez reposer 10 minutes.',
      'Versez le tout dans une poêle chaude et laissez prendre 5 minutes à feu doux.',
      'Retournez à l’aide d’une assiette et poursuivez 4 minutes.',
      'Le centre doit rester juste crémeux.',
    ],
    astuce: 'Elle se mange tiède ou froide, coupée en parts. C’est un des rares plats meilleurs deux heures après.',
  },
  {
    id: 'couscous-royal',
    titre: 'Couscous aux légumes et merguez',
    moment: 'diner',
    minutes: 90,
    kcal: 680,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch'],
    cuisine: 'orientale',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reception'],
    conservation: '3 jours au réfrigérateur, semoule à part',
    ingredients: [
      { nom: 'Semoule', quantite: '70 g crue', rayon: 'Épicerie' },
      { nom: 'Merguez', quantite: '2', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Blanc de poulet', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Navets', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Pois chiches cuits', quantite: '80 g', rayon: 'Épicerie' },
      { nom: 'Ras el-hanout', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Concentré de tomate', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites colorer le poulet, ajoutez le ras el-hanout et le concentré de tomate, puis mouillez à hauteur.',
      'Ajoutez carottes et navets, laissez cuire 30 minutes.',
      'Ajoutez la courgette et les pois chiches, 20 minutes de plus.',
      'Faites griller les merguez à part, à la poêle, et jetez leur graisse.',
      'Préparez la semoule : versez un volume d’eau bouillante salée pour un volume de graine, couvrez 5 minutes, puis égrenez à la fourchette avec un filet d’huile.',
      'Servez la semoule, les légumes et le bouillon à part, chacun se sert.',
    ],
    astuce: 'Le bouillon se sert à part, dans une saucière. Versé directement, il noie la semoule qu’on vient d’égrener.',
  },
  {
    id: 'tajine-poulet-citron',
    titre: 'Tajine de poulet au citron confit',
    moment: 'diner',
    minutes: 70,
    kcal: 540,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'orientale',
    gouts: ['acidule', 'epice'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reception'],
    regimes: ['sans-gluten', 'sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Cuisse de poulet', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Citron confit', quantite: '1/2', rayon: 'Épicerie' },
      { nom: 'Olives vertes', quantite: '10', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Gingembre moulu', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Curcuma', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Coriandre fraîche', quantite: '1 petit bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Semoule', quantite: '60 g crue', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir l’oignon avec les épices 5 minutes, jusqu’à ce que le parfum monte.',
      'Ajoutez le poulet, faites-le enrober, puis mouillez d’un verre d’eau.',
      'Couvrez et laissez mijoter 45 minutes à feu doux.',
      'Ajoutez le citron confit en lamelles et les olives rincées pour les 15 dernières minutes.',
      'Parsemez de coriandre et servez avec la semoule.',
    ],
    astuce: 'On n’utilise que l’écorce du citron confit ; la pulpe est trop salée et amère. Rincez aussi les olives, pour la même raison.',
  },
  {
    id: 'chakchouka',
    titre: 'Chakchouka',
    moment: 'diner',
    minutes: 35,
    kcal: 390,
    couvre: ['legume', 'proteine', 'feculent', 'matiere-grasse'],
    tags: ['vegetarien', 'une-casserole', 'rapide', 'economique'],
    cuisine: 'orientale',
    gouts: ['epice', 'releve'],
    typePlat: 'poelee',
    occasions: ['semaine'],
    regimes: ['vegetarien'],
    ingredients: [
      { nom: 'Poivrons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '4', rayon: 'Fruits et légumes' },
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Harissa', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Pain pita', quantite: '1', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Faites revenir oignon et poivrons 12 minutes, jusqu’à ce qu’ils s’attendrissent.',
      'Ajoutez les tomates, le cumin et la harissa, laissez réduire 10 minutes.',
      'Creusez deux puits dans la sauce et cassez-y les œufs.',
      'Couvrez et laissez 6 minutes : le blanc doit être pris, le jaune coulant.',
      'Servez à la poêle, avec le pain pour saucer.',
    ],
  },
  {
    id: 'houmous-falafel',
    titre: 'Assiette houmous et falafels',
    moment: 'dejeuner',
    minutes: 40,
    kcal: 610,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'nomade'],
    cuisine: 'orientale',
    gouts: ['epice', 'herbace'],
    typePlat: 'bowl',
    occasions: ['pique-nique', 'semaine'],
    regimes: ['vegetarien', 'vegan', 'sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Pois chiches cuits', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Tahini', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Coriandre fraîche', quantite: '1 bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Pain pita', quantite: '1', rayon: 'Boulangerie' },
      { nom: 'Tomate', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Mixez la moitié des pois chiches avec le tahini, le citron, l’ail et un peu d’eau glacée jusqu’à obtenir une crème lisse.',
      'Mixez l’autre moitié à peine, avec la coriandre et le cumin : la pâte à falafels doit rester grumeleuse pour tenir.',
      'Formez des boulettes et faites-les cuire au four 20 minutes à 200 °C, en les retournant à mi-cuisson.',
      'Servez le houmous en assiette creuse, les falafels dessus, avec la tomate en dés et le pain.',
    ],
    astuce: 'L’eau glacée est ce qui rend le houmous blanc et aérien. À l’eau tiède, il reste beige et compact.',
  },
  {
    id: 'moussaka',
    titre: 'Moussaka',
    moment: 'diner',
    minutes: 100,
    kcal: 610,
    couvre: ['proteine', 'legume', 'matiere-grasse'],
    tags: ['batch'],
    cuisine: 'mediterraneenne',
    gouts: ['epice', 'doux'],
    typePlat: 'gratin',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Aubergines', quantite: '1 grosse', rayon: 'Fruits et légumes' },
      { nom: 'Agneau haché', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Tomates concassées', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cannelle', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '15 cl', rayon: 'Crèmerie' },
      { nom: 'Farine', quantite: '12 g', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '12 g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites griller les tranches d’aubergine au four, 15 minutes à 220 °C.',
      'Préparez la sauce : oignon, agneau, tomates, cannelle, 30 minutes à feu doux.',
      'Montez en couches : aubergines, viande, aubergines.',
      'Nappez de béchamel et enfournez 40 minutes à 180 °C.',
      'Laissez reposer 15 minutes : c’est ce qui permet de servir des parts nettes.',
    ],
    astuce: 'La cannelle dans la viande est la signature grecque. Une pincée suffit — au-delà, le plat vire au dessert.',
  },
  {
    id: 'curry-poulet-coco',
    titre: 'Curry de poulet au lait de coco',
    moment: 'diner',
    minutes: 40,
    kcal: 590,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['une-casserole', 'batch'],
    cuisine: 'indienne',
    gouts: ['epice', 'doux'],
    typePlat: 'mijote',
    occasions: ['semaine'],
    regimes: ['sans-gluten', 'sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Blanc de poulet', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Lait de coco', quantite: '10 cl', rayon: 'Épicerie' },
      { nom: 'Curry en poudre', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Épinards', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Riz basmati', quantite: '60 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir oignon et gingembre, ajoutez le curry et laissez-le griller 1 minute.',
      'Ajoutez le poulet en morceaux et faites-le enrober.',
      'Versez le lait de coco et laissez frémir 15 minutes sans bouillir — il trancherait.',
      'Ajoutez les épinards en fin de cuisson, le temps qu’ils tombent.',
      'Servez avec le riz basmati.',
    ],
  },
  {
    id: 'dahl-lentilles-corail',
    titre: 'Dahl de lentilles corail',
    moment: 'diner',
    minutes: 35,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['vegetarien', 'batch', 'une-casserole', 'economique'],
    cuisine: 'indienne',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['semaine', 'reconfort'],
    regimes: ['vegetarien', 'vegan', 'sans-gluten', 'sans-lactose'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Lentilles corail', quantite: '80 g crues', rayon: 'Épicerie' },
      { nom: 'Lait de coco', quantite: '8 cl', rayon: 'Épicerie' },
      { nom: 'Tomates concassées', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Curcuma', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Riz basmati', quantite: '40 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir oignon et gingembre, ajoutez les épices et laissez-les chauffer 1 minute.',
      'Versez les lentilles rincées, les tomates et deux verres d’eau.',
      'Laissez cuire 20 minutes à couvert : les lentilles corail se défont, c’est normal et c’est le but.',
      'Ajoutez le lait de coco, laissez 5 minutes de plus et rectifiez le sel.',
      'Servez avec le riz.',
    ],
    astuce: 'Rincez les lentilles jusqu’à ce que l’eau soit claire : leur poussière d’amidon donne sinon un goût terreux.',
  },
  {
    id: 'pad-thai',
    titre: 'Pad thaï',
    moment: 'dejeuner',
    minutes: 30,
    kcal: 580,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['rapide', 'une-casserole'],
    cuisine: 'asiatique',
    gouts: ['sucre-sale', 'acidule'],
    typePlat: 'poelee',
    occasions: ['semaine'],
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Nouilles de riz', quantite: '70 g crues', rayon: 'Épicerie' },
      { nom: 'Crevettes', quantite: '100 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Germes de soja', quantite: '80 g', rayon: 'Fruits et légumes' },
      { nom: 'Cacahuètes', quantite: '15 g', rayon: 'Épicerie' },
      { nom: 'Nuoc-mâm', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron vert', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Sucre roux', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites tremper les nouilles 20 minutes dans l’eau tiède, jamais bouillante : elles finiront de cuire au wok.',
      'Mélangez nuoc-mâm, sucre et jus de citron vert : c’est la sauce, et l’équilibre des trois fait tout le plat.',
      'Saisissez les crevettes à feu vif, réservez. Brouillez l’œuf dans le wok.',
      'Ajoutez les nouilles égouttées et la sauce, remuez 2 minutes.',
      'Remettez les crevettes, ajoutez les germes de soja hors du feu pour qu’ils restent croquants.',
      'Parsemez de cacahuètes concassées et servez avec un quartier de citron vert.',
    ],
    astuce: 'Salé, sucré, acide : goûtez la sauce avant de la verser et ajustez. Aucune recette ne peut le faire à votre place, les nuoc-mâm varient du simple au double.',
  },
  {
    id: 'boeuf-wok-legumes',
    titre: 'Bœuf sauté au wok',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 520,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['rapide', 'une-casserole'],
    cuisine: 'asiatique',
    gouts: ['sucre-sale'],
    typePlat: 'poelee',
    occasions: ['semaine'],
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Bavette de bœuf', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Brocoli', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Poivron', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Nouilles chinoises', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Sauce soja', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Huile de sésame', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Coupez la viande en lanières fines en travers des fibres : c’est ce qui la rend tendre malgré une cuisson éclair.',
      'Faites chauffer le wok jusqu’à ce qu’il fume, puis saisissez la viande 90 secondes sans y toucher. Réservez.',
      'Faites sauter brocoli et poivron 4 minutes, à feu toujours vif.',
      'Remettez la viande, ajoutez les nouilles cuites, la sauce soja et le gingembre.',
      'Finissez par l’huile de sésame hors du feu — chauffée, elle devient amère.',
    ],
  },
  {
    id: 'ramen-poulet',
    titre: 'Ramen au poulet',
    moment: 'diner',
    minutes: 45,
    kcal: 520,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['une-casserole'],
    cuisine: 'asiatique',
    gouts: ['doux'],
    typePlat: 'soupe',
    occasions: ['reconfort', 'semaine'],
    ingredients: [
      { nom: 'Nouilles à ramen', quantite: '70 g crues', rayon: 'Épicerie' },
      { nom: 'Blanc de poulet', quantite: '100 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Bouillon de volaille', quantite: '50 cl', rayon: 'Épicerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Pousses d’épinard', quantite: '50 g', rayon: 'Fruits et légumes' },
      { nom: 'Sauce soja', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Ciboule', quantite: '2 tiges', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire l’œuf 6 minutes exactement et plongez-le dans l’eau glacée : le jaune reste coulant.',
      'Pochez le poulet 15 minutes dans le bouillon, puis émincez-le.',
      'Assaisonnez le bouillon à la sauce soja.',
      'Cuisez les nouilles à part et égouttez-les — cuites dans le bouillon, elles le troublent.',
      'Dressez : nouilles, bouillon brûlant, poulet, épinards, l’œuf coupé en deux, la ciboule.',
    ],
    astuce: 'Six minutes pour l’œuf, chronométrées. C’est la seule mesure du plat qui ne souffre aucune approximation.',
  },
  {
    id: 'nems-vietnamiens',
    titre: 'Nems au four et salade',
    moment: 'dejeuner',
    minutes: 50,
    kcal: 520,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['batch'],
    cuisine: 'asiatique',
    gouts: ['sucre-sale'],
    typePlat: 'roti',
    occasions: ['reception'],
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Galettes de riz', quantite: '4', rayon: 'Épicerie' },
      { nom: 'Porc haché', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Vermicelles de soja', quantite: '20 g', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Champignons noirs', quantite: '10 g secs', rayon: 'Épicerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
      { nom: 'Menthe fraîche', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
      { nom: 'Nuoc-mâm', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Réhydratez vermicelles et champignons, égouttez-les et hachez-les.',
      'Mélangez-les au porc et à la carotte râpée, salez.',
      'Humidifiez les galettes une par une et roulez les nems serrés, en rabattant les côtés.',
      'Badigeonnez d’huile et enfournez 25 minutes à 200 °C en les retournant : ils croustillent sans friture.',
      'Servez enroulés dans une feuille de salade avec la menthe, et le nuoc-mâm allongé d’eau à côté.',
    ],
    astuce: 'La feuille de salade autour du nem n’est pas une garniture : c’est ainsi qu’on les mange, et le contraste chaud-froid est le plat.',
  },
  {
    id: 'fish-and-chips',
    titre: 'Fish and chips au four',
    moment: 'diner',
    minutes: 50,
    kcal: 620,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['plaisir'],
    cuisine: 'britannique',
    gouts: ['acidule'],
    typePlat: 'roti',
    occasions: ['semaine'],
    ingredients: [
      { nom: 'Dos de cabillaud', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Chapelure', quantite: '30 g', rayon: 'Épicerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Farine', quantite: '15 g', rayon: 'Épicerie' },
      { nom: 'Huile de tournesol', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Petits pois', quantite: '80 g', rayon: 'Surgelés' },
    ],
    etapes: [
      'Coupez les pommes de terre en gros bâtonnets, séchez-les bien et enfournez-les 30 minutes à 220 °C avec l’huile.',
      'Panez le poisson : farine, œuf battu, chapelure, dans cet ordre et sans sauter d’étape.',
      'Ajoutez-le sur la plaque pour les 15 dernières minutes.',
      'Écrasez grossièrement les petits pois cuits à la fourchette, avec une pointe de beurre.',
      'Servez avec le citron.',
    ],
    astuce: 'Sécher les pommes de terre après les avoir coupées est ce qui décide de tout : l’eau en surface fait de la vapeur, et la vapeur empêche le croustillant.',
  },
  {
    id: 'shepherds-pie',
    titre: 'Shepherd’s pie',
    moment: 'diner',
    minutes: 75,
    kcal: 580,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['batch', 'economique'],
    cuisine: 'britannique',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['reconfort', 'semaine'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Agneau haché', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Petits pois', quantite: '60 g', rayon: 'Surgelés' },
      { nom: 'Concentré de tomate', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '5 cl', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites revenir oignon et carotte en dés, ajoutez la viande et laissez colorer.',
      'Ajoutez le concentré de tomate et un fond d’eau, laissez mijoter 20 minutes.',
      'Incorporez les petits pois en fin de cuisson.',
      'Préparez une purée avec le lait chaud, versez-la sur la viande et rayez la surface à la fourchette.',
      'Enfournez 25 minutes à 200 °C : les rayures dorent et croustillent.',
    ],
    astuce: 'Shepherd’s pie se fait à l’agneau, cottage pie au bœuf. Le nom dit le berger : ce n’est pas interchangeable.',
  },
  {
    id: 'burrito-haricots',
    titre: 'Burrito aux haricots noirs',
    moment: 'dejeuner',
    minutes: 30,
    kcal: 570,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['vegetarien', 'rapide', 'nomade'],
    cuisine: 'mexicaine',
    gouts: ['epice'],
    typePlat: 'sandwich',
    occasions: ['semaine', 'pique-nique'],
    regimes: ['vegetarien'],
    ingredients: [
      { nom: 'Tortilla de blé', quantite: '1 grande', rayon: 'Boulangerie' },
      { nom: 'Haricots noirs cuits', quantite: '120 g', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: '40 g cru', rayon: 'Épicerie' },
      { nom: 'Maïs doux', quantite: '50 g', rayon: 'Épicerie' },
      { nom: 'Avocat', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Citron vert', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Coriandre fraîche', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites revenir les haricots avec le cumin et écrasez-en une partie à la fourchette : c’est ce qui empêche la garniture de s’échapper.',
      'Mélangez le riz cuit avec la coriandre et le jus de citron vert.',
      'Réchauffez la tortilla 20 secondes à la poêle sèche pour qu’elle devienne souple.',
      'Garnissez au centre en laissant les bords libres, ajoutez l’avocat et le maïs.',
      'Repliez le bas, puis les côtés, et roulez serré.',
    ],
    astuce: 'Une tortilla froide craque au pliage. Vingt secondes à la poêle suffisent, et c’est la différence entre un burrito et un désastre.',
  },
  {
    id: 'poke-bowl-saumon',
    titre: 'Poke bowl au saumon',
    moment: 'dejeuner',
    minutes: 25,
    kcal: 560,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['sans-cuisson', 'nomade', 'rapide'],
    cuisine: 'asiatique',
    gouts: ['acidule', 'sucre-sale'],
    typePlat: 'bowl',
    occasions: ['semaine', 'pique-nique'],
    regimes: ['sans-lactose'],
    ingredients: [
      { nom: 'Saumon très frais', quantite: '110 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Riz rond', quantite: '60 g cru', rayon: 'Épicerie' },
      { nom: 'Avocat', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Concombre', quantite: '1/3', rayon: 'Fruits et légumes' },
      { nom: 'Edamames', quantite: '50 g', rayon: 'Surgelés' },
      { nom: 'Sauce soja', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Huile de sésame', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Graines de sésame', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Cuisez le riz, assaisonnez-le d’un filet de vinaigre de riz et laissez-le tiédir.',
      'Coupez le saumon en cubes réguliers et faites-le mariner 10 minutes dans la sauce soja et l’huile de sésame.',
      'Taillez concombre et avocat.',
      'Dressez le riz au fond, puis chaque élément dans son quartier.',
      'Parsemez de graines de sésame.',
    ],
    astuce: 'Le poisson doit être de qualité sushi et consommé le jour même. En cas de doute, passez au saumon fumé — le plat marche aussi.',
  },
  {
    id: 'gyoza-legumes',
    titre: 'Gyozas aux légumes',
    moment: 'dejeuner',
    minutes: 45,
    kcal: 460,
    couvre: ['feculent', 'legume', 'proteine'],
    tags: ['vegetarien', 'batch'],
    cuisine: 'asiatique',
    gouts: ['sucre-sale'],
    typePlat: 'poelee',
    occasions: ['reception'],
    regimes: ['vegetarien', 'sans-lactose'],
    ingredients: [
      { nom: 'Pâtes à gyoza', quantite: '10', rayon: 'Épicerie' },
      { nom: 'Chou chinois', quantite: '120 g', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Champignons noirs', quantite: '10 g secs', rayon: 'Épicerie' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Sauce soja', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Huile de sésame', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Hachez les légumes très finement, salez-les et laissez dégorger 15 minutes, puis pressez-les fort : une farce humide décolle la pâte.',
      'Mélangez avec le gingembre et l’huile de sésame.',
      'Garnissez chaque pâte d’une cuillère et pincez le bord en plis.',
      'Faites dorer les gyozas côté plat 2 minutes dans une poêle huilée.',
      'Versez un demi-verre d’eau, couvrez immédiatement et laissez 6 minutes : ils cuisent à la vapeur puis recroustillent quand l’eau s’évapore.',
      'Servez avec la sauce soja.',
    ],
    astuce: 'Dorer puis vapeur, dans cet ordre et sans jamais retourner : c’est toute la technique du gyoza, et elle tient en deux gestes.',
  },
  {
    id: 'goulash-hongrois',
    titre: 'Goulash',
    moment: 'diner',
    minutes: 150,
    kcal: 580,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'nordique',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['reconfort', 'dimanche'],
    regimes: ['sans-gluten'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Bœuf à braiser', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Paprika doux', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Poivron rouge', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Tomates concassées', quantite: '150 g', rayon: 'Épicerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Cumin', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites fondre les oignons 15 minutes : dans un goulash, il y a presque autant d’oignon que de viande, et c’est lui qui lie la sauce.',
      'Retirez la casserole du feu avant d’ajouter le paprika — il brûle en trois secondes sur un feu vif et devient amer.',
      'Remettez sur le feu, ajoutez la viande, le poivron et les tomates.',
      'Mouillez à hauteur et laissez mijoter 2 heures à couvert.',
      'Ajoutez les pommes de terre pour les 30 dernières minutes.',
    ],
    astuce: 'Le paprika hors du feu : c’est la seule règle non négociable du plat, et celle qu’on rate la première fois.',
  },
  {
    id: 'saumon-gravlax',
    titre: 'Saumon gravlax et pommes de terre',
    moment: 'dejeuner',
    minutes: 20,
    kcal: 480,
    couvre: ['proteine', 'feculent', 'legume', 'matiere-grasse'],
    tags: ['sans-cuisson', 'batch'],
    cuisine: 'nordique',
    gouts: ['herbace', 'fume'],
    typePlat: 'salade',
    occasions: ['reception', 'fete'],
    regimes: ['sans-gluten'],
    ingredients: [
      { nom: 'Saumon gravlax', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Crème légère 15 %', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Aneth', quantite: '1 petit bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Moutarde', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Citron', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire les pommes de terre à l’eau et laissez-les tiédir : elles absorbent la sauce mieux tièdes que froides.',
      'Mélangez crème, moutarde, aneth haché et jus de citron.',
      'Nappez les pommes de terre de sauce.',
      'Dressez le saumon en tranches fines à côté, avec la salade.',
    ],
  },
]
