import type { Recette } from '../types'

/**
 * Le terroir du Nord et de l'Ouest : Flandre et Belgique, Bretagne, Normandie,
 * Alsace, Lorraine, Val de Loire.
 *
 * Quantités et calories **pour une personne**, comme partout dans le catalogue.
 * Un plat mijoté se cuisine rarement pour un seul convive : `ingredientsPour()`
 * multiplie les quantités à l'affichage, et les étapes sont écrites pour que la
 * multiplication ne les rende pas fausses — d'où « à hauteur » plutôt qu'un
 * volume de liquide figé.
 */
export const TERROIR_NORD: Recette[] = [
  {
    id: 'carbonade-flamande',
    titre: 'Carbonade flamande',
    moment: 'diner',
    minutes: 180,
    kcal: 680,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['sucre-sale', 'doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    difficulte: 'facile',
    conservation: '4 jours au réfrigérateur, 3 mois au congélateur',
    rechauffage: 'À la cocotte à feu doux. Elle est meilleure le lendemain, et ce n’est pas une formule : la sauce continue de lier en refroidissant.',
    substitutions: [
      { ingredient: 'Bière brune', par: 'bière blonde', effet: 'moins amer, moins profond — allongez d’une cuillère de cassonade' },
      { ingredient: 'Pain d’épices', par: 'tranche de pain de campagne + 1 CàC de miel', effet: 'la sauce lie un peu moins, la couleur est plus claire' },
    ],
    ingredients: [
      { nom: 'Bœuf à braiser', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '2 moyens', rayon: 'Fruits et légumes' },
      { nom: 'Bière brune', quantite: '20 cl', rayon: 'Épicerie' },
      { nom: 'Pain d’épices', quantite: '1 tranche', rayon: 'Boulangerie' },
      { nom: 'Moutarde', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Cassonade', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Thym et laurier', quantite: '1 branche, 1 feuille', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Coupez la viande en gros cubes et séchez-les dans du papier absorbant : une viande humide bout au lieu de dorer, et c’est la coloration qui fait toute la sauce.',
      'Faites-les colorer dans le beurre à feu vif, sur toutes les faces, puis réservez.',
      'Émincez les oignons et faites-les fondre 10 minutes dans la même cocotte, sans les brûler, en grattant les sucs.',
      'Remettez la viande, saupoudrez de cassonade, versez la bière à hauteur et ajoutez le thym et le laurier.',
      'Tartinez le pain d’épices de moutarde et posez-le en surface, face moutardée vers le bas : il fondra tout seul et liera la sauce, sans farine.',
      'Couvrez et laissez mijoter 2 h 30 à feu très doux. Goûtez avant de saler — la bière réduit et concentre.',
      'Servez avec les pommes de terre cuites à l’eau.',
    ],
    astuce: 'Le sucre n’est pas là pour sucrer mais pour tenir tête à l’amertume de la bière. Sans lui, la sauce reste âpre ; avec, elle devient ronde.',
  },
  {
    id: 'waterzooi-poulet',
    titre: 'Waterzooï de poulet',
    moment: 'diner',
    minutes: 60,
    kcal: 540,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    region: 'belgique',
    gouts: ['doux', 'herbace'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '2 jours au réfrigérateur',
    rechauffage: 'À feu doux sans jamais bouillir : la crème et le jaune d’œuf trancheraient.',
    ingredients: [
      { nom: 'Cuisse de poulet', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poireau', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Céleri branche', quantite: '1 branche', rayon: 'Fruits et légumes' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Jaune d’œuf', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Persil', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites pocher le poulet 30 minutes dans de l’eau à hauteur, avec le vert du poireau et une carotte coupée en deux.',
      'Retirez le poulet, filtrez le bouillon et remettez-le dans la cocotte.',
      'Taillez les légumes en bâtonnets réguliers et faites-les cuire 15 minutes dans le bouillon.',
      'Effilochez le poulet sans la peau et remettez-le avec les légumes.',
      'Hors du feu, mélangez la crème et le jaune d’œuf avec une louche de bouillon chaud, puis reversez le tout dans la cocotte en remuant.',
      'Réchauffez sans bouillir, parsemez de persil et servez en assiette creuse.',
    ],
    astuce: 'Le waterzooï est une soupe qui s’est étoffée : servez-le assez liquide, avec une cuillère à côté de la fourchette.',
  },
  {
    id: 'potjevleesch',
    titre: 'Potjevleesch et salade',
    moment: 'dejeuner',
    minutes: 20,
    kcal: 430,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['sans-cuisson', 'rapide'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['acidule'],
    typePlat: 'salade',
    occasions: ['semaine'],
    ingredients: [
      { nom: 'Potjevleesch', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
      { nom: 'Cornichons', quantite: '4', rayon: 'Épicerie' },
      { nom: 'Pain de campagne', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Moutarde', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Vinaigre de cidre', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Sortez le potjevleesch du réfrigérateur 10 minutes avant : la gelée doit rester ferme mais le goût a besoin de se réveiller.',
      'Assaisonnez la salade d’une vinaigrette à la moutarde, sans huile ou presque — la terrine en apporte assez.',
      'Découpez le potjevleesch en tranches épaisses, sans chercher à démouler proprement.',
      'Servez avec les cornichons et le pain grillé.',
    ],
    astuce: 'Traditionnellement servi froid, même en hiver. Le réchauffer ferait fondre la gelée, qui est tout l’intérêt du plat.',
  },
  {
    id: 'moules-mariniere',
    titre: 'Moules marinières',
    moment: 'diner',
    minutes: 25,
    kcal: 470,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['rapide', 'une-casserole'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['herbace'],
    typePlat: 'mijote',
    occasions: ['semaine', 'reception'],
    regimes: ['sans-gluten'],
    ingredients: [
      { nom: 'Moules', quantite: '500 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Échalotes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc sec', quantite: '10 cl', rayon: 'Épicerie' },
      { nom: 'Persil plat', quantite: '1 petit bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Grattez et rincez les moules à grande eau. Jetez celles qui restent ouvertes quand vous les tapotez.',
      'Faites suer les échalotes ciselées dans le beurre, 3 minutes, sans coloration.',
      'Versez le vin blanc, portez à ébullition, puis ajoutez les moules d’un coup.',
      'Couvrez et laissez 5 minutes à feu vif, en secouant la casserole une fois. Elles sont prêtes dès qu’elles sont ouvertes — au-delà, elles caoutchoutent.',
      'Parsemez de persil et servez avec les pommes de terre vapeur.',
    ],
    astuce: 'Ne salez jamais : l’eau de mer des moules assaisonne le jus toute seule, et souvent largement.',
  },
  {
    id: 'welsh',
    titre: 'Welsh du Nord',
    moment: 'diner',
    minutes: 25,
    kcal: 720,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['plaisir'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['fume', 'doux'],
    typePlat: 'gratin',
    occasions: ['reconfort'],
    ingredients: [
      { nom: 'Cheddar', quantite: '120 g', rayon: 'Crèmerie' },
      { nom: 'Jambon blanc', quantite: '1 tranche épaisse', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pain de campagne', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Bière blonde', quantite: '5 cl', rayon: 'Épicerie' },
      { nom: 'Moutarde', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Préchauffez le four en position gril.',
      'Faites fondre le cheddar coupé en dés avec la bière et la moutarde, à feu très doux, en remuant sans arrêt.',
      'Posez le pain grillé au fond d’un plat allant au four, couvrez du jambon.',
      'Versez le cheddar fondu par-dessus et passez 5 minutes sous le gril, jusqu’à ce que le dessus boursoufle et dore.',
      'Servez brûlant avec la salade, qui n’est pas un accompagnement mais un contrepoids.',
    ],
    astuce: 'Le fromage doit fondre, jamais bouillir : au-delà, il rend son gras et la sauce se sépare.',
  },
  {
    id: 'endives-jambon-gratin',
    titre: 'Endives au jambon gratinées',
    moment: 'diner',
    minutes: 50,
    kcal: 490,
    couvre: ['proteine', 'legume', 'matiere-grasse'],
    tags: ['batch'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['semaine', 'reconfort'],
    conservation: '2 jours au réfrigérateur',
    rechauffage: '15 min à 180 °C. Le micro-ondes rend la béchamel granuleuse.',
    ingredients: [
      { nom: 'Endives', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Jambon blanc', quantite: '3 tranches', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Lait demi-écrémé', quantite: '20 cl', rayon: 'Crèmerie' },
      { nom: 'Farine', quantite: '15 g', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '15 g', rayon: 'Crèmerie' },
      { nom: 'Emmental râpé', quantite: '20 g', rayon: 'Crèmerie' },
      { nom: 'Noix de muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Creusez le cône dur à la base de chaque endive : c’est lui qui porte toute l’amertume.',
      'Faites-les cuire 20 minutes à la vapeur, puis pressez-les entre vos mains pour en chasser l’eau — une endive gorgée d’eau noie le gratin.',
      'Préparez la béchamel : beurre fondu, farine, deux minutes de cuisson, puis le lait froid versé d’un coup en fouettant. Muscade, sel, poivre.',
      'Enroulez chaque endive dans une tranche de jambon et rangez-les serrées dans un plat.',
      'Nappez de béchamel, parsemez d’emmental et enfournez 25 minutes à 200 °C.',
    ],
    astuce: 'Le lait froid sur un roux chaud, versé d’un coup : c’est le seul ordre qui ne fait pas de grumeaux.',
  },
  {
    id: 'flamiche-poireaux',
    titre: 'Flamiche aux poireaux',
    moment: 'dejeuner',
    minutes: 60,
    kcal: 520,
    couvre: ['legume', 'feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'nomade'],
    cuisine: 'francaise',
    region: 'nord',
    gouts: ['doux'],
    typePlat: 'tarte',
    occasions: ['semaine', 'pique-nique'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Pâte brisée', quantite: '1/4 de rouleau', rayon: 'Crèmerie' },
      { nom: 'Poireaux', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '4 CàS', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Noix de muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Émincez finement les poireaux, blanc et vert tendre, et lavez-les à grande eau.',
      'Faites-les fondre 20 minutes au beurre à couvert, à feu doux : ils doivent compoter, pas frire.',
      'Laissez tiédir, puis mélangez avec l’œuf battu, la crème et la muscade.',
      'Garnissez le moule chemisé de pâte et enfournez 35 minutes à 180 °C.',
      'Attendez 10 minutes avant de couper : l’appareil finit de prendre en refroidissant.',
    ],
    astuce: 'Ne versez jamais un appareil chaud sur une pâte crue — elle se détrempe avant même d’entrer au four.',
  },
  {
    id: 'galette-complete',
    titre: 'Galette complète',
    moment: 'diner',
    minutes: 25,
    kcal: 500,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['rapide'],
    cuisine: 'francaise',
    region: 'bretagne',
    gouts: ['doux'],
    typePlat: 'sandwich',
    occasions: ['semaine'],
    ingredients: [
      { nom: 'Galette de sarrasin', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Jambon blanc', quantite: '2 tranches', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Emmental râpé', quantite: '30 g', rayon: 'Crèmerie' },
      { nom: 'Beurre demi-sel', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Chauffez une grande poêle à feu vif avec une noisette de beurre.',
      'Posez la galette, cassez l’œuf au centre et étalez le blanc à la spatule sans toucher au jaune.',
      'Répartissez le fromage et le jambon autour, salez, poivrez.',
      'Rabattez les quatre côtés en carré dès que le blanc est pris — le jaune doit rester coulant.',
      'Servez immédiatement avec la salade.',
    ],
    astuce: 'Une galette qui attend ramollit. C’est le seul plat où l’on fait patienter les convives, jamais l’inverse.',
  },
  {
    id: 'kig-ha-farz',
    titre: 'Kig ha farz allégé',
    moment: 'diner',
    minutes: 150,
    kcal: 620,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'bretagne',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Jarret de porc', quantite: '120 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Poireau', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Chou vert', quantite: '1/4', rayon: 'Fruits et légumes' },
      { nom: 'Farine de sarrasin', quantite: '50 g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '10 cl', rayon: 'Crèmerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites cuire le jarret 1 h 30 dans un grand volume d’eau, à frémissement.',
      'Préparez le farz : mélangez la farine de sarrasin, l’œuf et le lait jusqu’à obtenir une pâte souple, salez.',
      'Versez-la dans un sac à farz — un torchon fin noué convient — sans le remplir : la pâte gonfle.',
      'Plongez le sac dans le bouillon et ajoutez les légumes taillés en gros morceaux.',
      'Laissez cuire 1 heure, puis démoulez le farz en l’émiettant à travers le torchon.',
      'Servez la viande, les légumes et le farz émietté arrosés d’une louche de bouillon.',
    ],
    astuce: 'Le farz s’émiette, il ne se tranche pas. Une tranche nette veut dire qu’il a trop cuit.',
  },
  {
    id: 'saint-jacques-bretonne',
    titre: 'Saint-Jacques à la bretonne',
    moment: 'diner',
    minutes: 30,
    kcal: 430,
    couvre: ['proteine', 'legume', 'matiere-grasse', 'feculent'],
    tags: ['rapide'],
    cuisine: 'francaise',
    region: 'bretagne',
    gouts: ['doux', 'herbace'],
    typePlat: 'poelee',
    occasions: ['reception', 'fete'],
    ingredients: [
      { nom: 'Noix de Saint-Jacques', quantite: '6', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Échalotes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Cidre brut', quantite: '5 cl', rayon: 'Épicerie' },
      { nom: 'Crème légère 15 %', quantite: '2 CàS', rayon: 'Crèmerie' },
      { nom: 'Beurre demi-sel', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Ciboulette', quantite: 'quelques brins', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Séchez les noix dans du papier absorbant — c’est la condition d’une vraie coloration.',
      'Saisissez-les 1 minute par face dans le beurre très chaud, puis réservez-les au chaud.',
      'Dans la même poêle, faites fondre les échalotes ciselées 3 minutes.',
      'Déglacez au cidre, laissez réduire de moitié, ajoutez la crème et donnez un bouillon.',
      'Nappez les noix de sauce, parsemez de ciboulette, servez avec le riz.',
    ],
    astuce: 'Deux minutes de cuisson au total, pas trois : une Saint-Jacques trop cuite devient sèche et perd tout son sucre.',
  },
  {
    id: 'cotriade',
    titre: 'Cotriade bretonne',
    moment: 'diner',
    minutes: 55,
    kcal: 480,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['une-casserole', 'batch'],
    cuisine: 'francaise',
    region: 'bretagne',
    gouts: ['doux'],
    typePlat: 'soupe',
    occasions: ['dimanche', 'reconfort'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Filets de poisson blanc', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Maquereau', quantite: '1 filet', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Beurre demi-sel', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Thym et laurier', quantite: '1 branche, 1 feuille', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites fondre l’oignon émincé dans le beurre, sans coloration.',
      'Ajoutez les pommes de terre en gros morceaux, couvrez d’eau à hauteur, thym et laurier.',
      'Laissez cuire 20 minutes, jusqu’à ce que la pointe du couteau entre sans résistance.',
      'Ajoutez d’abord les poissons fermes, puis les plus fragiles 4 minutes plus tard.',
      'Coupez le feu dès que la chair se détache et laissez reposer 5 minutes à couvert.',
      'Servez le bouillon en assiette creuse, poisson et pommes de terre par-dessus.',
    ],
    astuce: 'C’était le plat des pêcheurs, fait des poissons invendus : n’importe quel mélange marche, à condition d’ajouter les chairs fragiles en dernier.',
  },
  {
    id: 'far-breton-leger',
    titre: 'Far breton aux pruneaux',
    moment: 'collation',
    minutes: 60,
    kcal: 240,
    couvre: ['feculent', 'fruit', 'proteine'],
    tags: ['batch', 'economique'],
    cuisine: 'francaise',
    region: 'bretagne',
    gouts: ['doux'],
    occasions: ['dimanche'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Farine', quantite: '30 g', rayon: 'Épicerie' },
      { nom: 'Lait demi-écrémé', quantite: '15 cl', rayon: 'Crèmerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Pruneaux', quantite: '4', rayon: 'Épicerie' },
      { nom: 'Sucre', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Fouettez la farine, le sucre et l’œuf, puis versez le lait petit à petit pour éviter les grumeaux.',
      'Laissez reposer la pâte 30 minutes : elle sera plus lisse et le far moins caoutchouteux.',
      'Répartissez les pruneaux dans un plat beurré et versez la pâte dessus.',
      'Enfournez 45 minutes à 180 °C. Le far doit trembler légèrement au centre en sortant.',
    ],
    astuce: 'Il se mange tiède ou froid, jamais chaud : c’est en refroidissant qu’il prend sa texture dense.',
  },
  {
    id: 'poulet-vallee-auge',
    titre: 'Poulet vallée d’Auge',
    moment: 'diner',
    minutes: 60,
    kcal: 560,
    couvre: ['proteine', 'legume', 'fruit', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    region: 'normandie',
    gouts: ['doux', 'acidule'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reception'],
    regimes: ['sans-gluten'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Cuisse de poulet', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pomme', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Champignons de Paris', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Cidre brut', quantite: '15 cl', rayon: 'Épicerie' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites dorer le poulet dans le beurre sur toutes ses faces, 8 minutes, puis réservez.',
      'Faites revenir les champignons émincés à feu vif jusqu’à évaporation de leur eau.',
      'Remettez le poulet, versez le cidre, couvrez et laissez mijoter 30 minutes.',
      'Ajoutez la pomme en quartiers pour les 10 dernières minutes : plus tôt, elle se transforme en compote.',
      'Retirez la viande, incorporez la crème au jus et laissez réduire 3 minutes.',
      'Nappez et servez avec le riz.',
    ],
    astuce: 'Cidre brut et non doux : le sucre du cidre doux caramélise et masque l’acidité qui fait tout l’équilibre du plat.',
  },
  {
    id: 'sole-normande',
    titre: 'Sole à la normande',
    moment: 'diner',
    minutes: 35,
    kcal: 460,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    cuisine: 'francaise',
    tags: [],
    region: 'normandie',
    gouts: ['doux'],
    typePlat: 'poelee',
    occasions: ['reception', 'fete'],
    ingredients: [
      { nom: 'Sole', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Moules', quantite: '200 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Crevettes', quantite: '60 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Cidre brut', quantite: '10 cl', rayon: 'Épicerie' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Ouvrez les moules au cidre à feu vif, 5 minutes, puis décoquillez-les et filtrez le jus.',
      'Faites cuire la sole au beurre à feu moyen, 4 minutes par face.',
      'Faites réduire le jus de moules de moitié, ajoutez la crème et laissez épaissir.',
      'Ajoutez moules et crevettes juste pour les réchauffer, sans les cuire une seconde fois.',
      'Nappez la sole et servez avec les pommes de terre vapeur.',
    ],
    astuce: 'Filtrez toujours le jus de moules : il porte du sable, et c’est lui qui gâche un plat par ailleurs impeccable.',
  },
  {
    id: 'tripes-caen-allegees',
    titre: 'Tripes à la mode de Caen',
    moment: 'diner',
    minutes: 240,
    kcal: 520,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'normandie',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche'],
    conservation: '4 jours au réfrigérateur',
    rechauffage: 'À feu doux à la cocotte, 20 minutes.',
    ingredients: [
      { nom: 'Tripes préparées', quantite: '200 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Cidre brut', quantite: '20 cl', rayon: 'Épicerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Thym et laurier', quantite: '1 branche, 1 feuille', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Rangez les tripes, les carottes en rondelles et l’oignon émincé en couches dans une cocotte.',
      'Mouillez au cidre à hauteur, ajoutez thym et laurier, salez peu.',
      'Fermez hermétiquement — un papier cuisson sous le couvercle suffit — et enfournez 4 heures à 140 °C.',
      'Vérifiez à mi-cuisson qu’il reste du liquide, et complétez à l’eau si besoin.',
      'Servez très chaud avec les pommes de terre.',
    ],
    astuce: 'Une cuisson longue et basse, jamais forte : c’est le seul moyen d’attendrir les tripes sans les dessécher.',
  },
  {
    id: 'choucroute-garnie',
    titre: 'Choucroute garnie',
    moment: 'diner',
    minutes: 90,
    kcal: 750,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'alsace',
    gouts: ['acidule', 'fume'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    rechauffage: 'À la cocotte à couvert, 20 minutes à feu doux.',
    ingredients: [
      { nom: 'Choucroute crue', quantite: '250 g', rayon: 'Épicerie' },
      { nom: 'Saucisse de Strasbourg', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Saucisse de Montbéliard', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Jambonneau', quantite: '80 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc d’Alsace', quantite: '15 cl', rayon: 'Épicerie' },
      { nom: 'Baies de genièvre', quantite: '5', rayon: 'Épicerie' },
    ],
    etapes: [
      'Rincez la choucroute à l’eau froide et pressez-la : elle sera acidulée et non acide.',
      'Disposez-la dans une cocotte avec le genièvre et le vin blanc, sans eau.',
      'Enfouissez le jambonneau au milieu, couvrez et laissez cuire 1 heure à feu doux.',
      'Ajoutez les saucisses et les pommes de terre pour les 25 dernières minutes — plus longtemps, les saucisses éclatent.',
      'Dressez la choucroute au centre du plat, les viandes autour.',
    ],
    astuce: 'Le rinçage se dose : trop bref, le plat est agressif ; trop long, il perd le goût de la fermentation qui fait la choucroute.',
  },
  {
    id: 'baeckeoffe',
    titre: 'Baeckeoffe',
    moment: 'diner',
    minutes: 210,
    kcal: 640,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'alsace',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Épaule d’agneau', quantite: '60 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Échine de porc', quantite: '60 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Bœuf à braiser', quantite: '60 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Poireau', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc d’Alsace', quantite: '15 cl', rayon: 'Épicerie' },
    ],
    etapes: [
      'La veille, faites mariner les trois viandes en cubes dans le vin blanc avec l’oignon émincé.',
      'Le jour même, alternez dans une terrine des couches de pommes de terre en rondelles, de viande et de poireau.',
      'Terminez par une couche de pommes de terre, versez la marinade filtrée à hauteur.',
      'Fermez la terrine et lutez le couvercle avec un boudin de pâte à pain, ou à défaut deux épaisseurs de papier cuisson.',
      'Enfournez 3 heures à 160 °C, sans jamais ouvrir : toute la cuisson tient à la vapeur enfermée.',
    ],
    astuce: 'Le nom veut dire « four du boulanger » : les ménagères déposaient la terrine chez lui le matin et la récupéraient à midi. La cuisson longue et fermée est le plat, pas un détail.',
  },
  {
    id: 'tarte-flambee',
    titre: 'Tarte flambée',
    moment: 'diner',
    minutes: 25,
    kcal: 520,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['rapide', 'plaisir'],
    cuisine: 'francaise',
    region: 'alsace',
    gouts: ['fume', 'doux'],
    typePlat: 'tarte',
    occasions: ['reception', 'semaine'],
    ingredients: [
      { nom: 'Pâte à pain fine', quantite: '80 g', rayon: 'Boulangerie' },
      { nom: 'Fromage blanc 3 %', quantite: '60 g', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '1 CàS', rayon: 'Crèmerie' },
      { nom: 'Lardons fumés', quantite: '40 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Noix de muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Préchauffez le four au maximum, avec la plaque à l’intérieur : c’est la chaleur du support qui cuit le dessous.',
      'Étalez la pâte le plus finement possible, presque transparente.',
      'Mélangez fromage blanc, crème et muscade, étalez en couche mince en laissant un bord libre.',
      'Répartissez les lardons et l’oignon émincé cru.',
      'Enfournez 10 minutes sur la plaque brûlante, jusqu’à ce que les bords noircissent par endroits.',
    ],
    astuce: 'Les bords doivent brûler un peu : une flammekueche uniformément dorée n’a pas eu assez chaud.',
  },
  {
    id: 'spaetzle-gratines',
    titre: 'Spätzle gratinés au munster',
    moment: 'diner',
    minutes: 40,
    kcal: 620,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'plaisir'],
    cuisine: 'francaise',
    region: 'alsace',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['reconfort'],
    ingredients: [
      { nom: 'Spätzle', quantite: '180 g cuits', rayon: 'Épicerie' },
      { nom: 'Munster', quantite: '50 g', rayon: 'Crèmerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Cumin', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites blondir l’oignon émincé au beurre, 10 minutes à feu doux — c’est long, et c’est ce qui donne le goût.',
      'Mélangez les spätzle cuits avec l’oignon et la crème.',
      'Versez dans un plat, couvrez de munster en lamelles et saupoudrez de cumin.',
      'Enfournez 15 minutes à 200 °C, jusqu’à ce que le fromage soit fondu et coloré.',
    ],
    astuce: 'Le cumin avec le munster n’est pas une fantaisie : c’est l’accord traditionnel, et il coupe le gras du fromage.',
  },
  {
    id: 'quiche-lorraine',
    titre: 'Quiche lorraine',
    moment: 'dejeuner',
    minutes: 55,
    kcal: 580,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['batch', 'nomade'],
    cuisine: 'francaise',
    region: 'lorraine',
    gouts: ['fume', 'doux'],
    typePlat: 'tarte',
    occasions: ['semaine', 'pique-nique'],
    conservation: '2 jours au réfrigérateur',
    rechauffage: '10 min à 180 °C. Elle se mange aussi bien froide.',
    ingredients: [
      { nom: 'Pâte brisée', quantite: '1/4 de rouleau', rayon: 'Crèmerie' },
      { nom: 'Lardons fumés', quantite: '60 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '6 CàS', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: '5 cl', rayon: 'Crèmerie' },
      { nom: 'Noix de muscade', quantite: '1 pincée', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir les lardons à sec 5 minutes et jetez la graisse rendue.',
      'Piquez la pâte, couvrez de papier cuisson et de légumes secs, puis faites-la cuire à blanc 12 minutes à 180 °C.',
      'Battez œufs, crème, lait et muscade. Salez à peine : les lardons salent déjà.',
      'Répartissez les lardons sur le fond précuit, versez l’appareil.',
      'Enfournez 30 minutes à 180 °C, jusqu’à ce que le centre soit juste pris.',
    ],
    astuce: 'Pas de fromage dans une vraie quiche lorraine — c’est ce qui la distingue de toutes les autres. Le débat est ancien, la recette est claire.',
  },
  {
    id: 'potee-lorraine',
    titre: 'Potée lorraine',
    moment: 'diner',
    minutes: 120,
    kcal: 590,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'lorraine',
    gouts: ['fume'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Palette de porc fumée', quantite: '100 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Chou vert', quantite: '1/4', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Navets', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Haricots blancs cuits', quantite: '80 g', rayon: 'Épicerie' },
      { nom: 'Thym et laurier', quantite: '1 branche, 1 feuille', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites dessaler la palette 1 heure à l’eau froide si elle est très salée, puis mettez-la à cuire 1 heure à frémissement.',
      'Blanchissez le chou 5 minutes à l’eau bouillante et jetez cette eau : elle emporte l’amertume et ce qui rend le chou difficile à digérer.',
      'Ajoutez au bouillon les carottes, le navet et le chou. Comptez 30 minutes.',
      'Ajoutez les pommes de terre et les haricots pour les 20 dernières minutes.',
      'Servez la viande tranchée au centre, les légumes en couronne, avec une louche de bouillon.',
    ],
    astuce: 'Goûtez le bouillon avant de saler, jamais avant la fin : la viande fumée relargue son sel toute la cuisson.',
  },
  {
    id: 'rillettes-tours-tartine',
    titre: 'Tartine de rillettes et crudités',
    moment: 'dejeuner',
    minutes: 10,
    kcal: 460,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['rapide', 'sans-cuisson', 'nomade'],
    cuisine: 'francaise',
    region: 'val-de-loire',
    gouts: ['fume'],
    typePlat: 'sandwich',
    occasions: ['semaine', 'pique-nique'],
    ingredients: [
      { nom: 'Rillettes', quantite: '50 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pain de campagne', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Cornichons', quantite: '4', rayon: 'Épicerie' },
      { nom: 'Radis', quantite: '6', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites griller le pain : les rillettes fondent légèrement au contact et s’étalent seules.',
      'Étalez sans écraser, en gardant les fibres visibles.',
      'Servez avec les radis, les cornichons et la salade.',
    ],
    astuce: 'Sortez les rillettes 15 minutes avant : au sortir du frigo, le gras est figé et le goût reste muet.',
  },
  {
    id: 'sandre-beurre-blanc',
    titre: 'Sandre au beurre blanc',
    moment: 'diner',
    minutes: 35,
    kcal: 490,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: [],
    cuisine: 'francaise',
    region: 'val-de-loire',
    gouts: ['acidule'],
    typePlat: 'poelee',
    occasions: ['reception'],
    regimes: ['sans-gluten'],
    ingredients: [
      { nom: 'Filet de sandre', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Échalotes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc sec', quantite: '5 cl', rayon: 'Épicerie' },
      { nom: 'Vinaigre de vin blanc', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '25 g', rayon: 'Crèmerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Épinards', quantite: '150 g', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites réduire les échalotes ciselées avec le vin et le vinaigre jusqu’à ce qu’il ne reste qu’une cuillère de liquide.',
      'Hors du feu, incorporez le beurre très froid en petits morceaux, un à un, en fouettant sans arrêt.',
      'Gardez la sauce au tiède, jamais au chaud : au-dessus de 60 °C elle se sépare, et rien ne la rattrape.',
      'Faites cuire le sandre à la poêle, côté peau d’abord, 4 minutes, puis 2 minutes de l’autre.',
      'Servez avec les épinards tombés à la poêle et les pommes de terre vapeur.',
    ],
    astuce: 'Beurre froid, casserole tiède, fouet continu : les trois conditions du beurre blanc. En rater une le fait trancher.',
  },
  {
    id: 'poulet-basquaise-nord',
    titre: 'Fricassée de volaille aux champignons',
    moment: 'diner',
    minutes: 45,
    kcal: 520,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    region: 'val-de-loire',
    gouts: ['doux', 'herbace'],
    typePlat: 'mijote',
    occasions: ['semaine'],
    ingredients: [
      { nom: 'Blanc de poulet', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Champignons de Paris', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Échalotes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc sec', quantite: '8 cl', rayon: 'Épicerie' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Estragon', quantite: 'quelques feuilles', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites dorer le poulet en gros morceaux 5 minutes, puis réservez.',
      'Saisissez les champignons à feu vif dans la même poêle, sans les remuer au début : c’est comme ça qu’ils dorent au lieu de rendre leur eau.',
      'Ajoutez les échalotes, déglacez au vin blanc et laissez réduire de moitié.',
      'Remettez le poulet, ajoutez la crème et laissez frémir 10 minutes.',
      'Parsemez d’estragon hors du feu et servez avec le riz.',
    ],
    astuce: 'L’estragon ne se cuit pas. Ajouté à froid, il parfume ; ajouté à chaud, il devient amer.',
  },
]
