import type { Recette } from '../types'

/**
 * Le terroir du Centre, de l'Est et du Sud : Bourgogne, Lyonnais, Savoie,
 * Auvergne, Provence, Sud-Ouest, Pays basque, Languedoc, Corse, et les outre-mer.
 *
 * Quantités et calories pour une personne — voir l'en-tête de `nord.ts`.
 */
export const TERROIR_SUD: Recette[] = [
  {
    id: 'boeuf-bourguignon',
    titre: 'Bœuf bourguignon',
    moment: 'diner',
    minutes: 195,
    kcal: 660,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'bourgogne',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '4 jours au réfrigérateur, 3 mois au congélateur',
    rechauffage: 'À la cocotte à feu doux, 20 minutes. Meilleur réchauffé.',
    ingredients: [
      { nom: 'Bœuf à braiser', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Vin rouge corsé', quantite: '20 cl', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Champignons de Paris', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Lardons', quantite: '30 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Bouquet garni', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Séchez la viande en cubes et faites-la colorer par petites quantités : une cocotte surchargée fait bouillir au lieu de saisir.',
      'Faites revenir lardons, oignon et carottes, puis remettez la viande.',
      'Versez le vin à hauteur, ajoutez le bouquet garni et portez à frémissement.',
      'Couvrez et laissez mijoter 2 h 30 à feu très doux, ou au four à 150 °C.',
      'Faites sauter les champignons à part et ajoutez-les 15 minutes avant la fin, pour qu’ils gardent leur tenue.',
      'Servez avec les pommes de terre vapeur.',
    ],
    astuce: 'Le vin doit être buvable. Un vin de cuisine médiocre ne s’améliore pas en réduisant — il concentre ses défauts.',
  },
  {
    id: 'oeufs-meurette',
    titre: 'Œufs en meurette',
    moment: 'diner',
    minutes: 45,
    kcal: 470,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: [],
    cuisine: 'francaise',
    region: 'bourgogne',
    gouts: ['doux'],
    typePlat: 'poelee',
    occasions: ['reception'],
    ingredients: [
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Vin rouge', quantite: '15 cl', rayon: 'Épicerie' },
      { nom: 'Lardons', quantite: '40 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Échalotes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Champignons de Paris', quantite: '80 g', rayon: 'Fruits et légumes' },
      { nom: 'Pain de campagne', quantite: '2 tranches', rayon: 'Boulangerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Faites revenir lardons, échalotes et champignons, puis versez le vin et laissez réduire de moitié.',
      'Pochez les œufs dans de l’eau frémissante vinaigrée, 3 minutes, en créant un tourbillon avant de les glisser.',
      'Montez la sauce au beurre froid hors du feu.',
      'Posez les œufs sur le pain grillé et nappez de sauce.',
    ],
    astuce: 'Des œufs très frais tiennent seuls au pochage. Passé une semaine, le blanc s’effiloche quoi qu’on fasse.',
  },
  {
    id: 'gougeres',
    titre: 'Gougères au comté',
    moment: 'collation',
    minutes: 40,
    kcal: 210,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'batch'],
    cuisine: 'francaise',
    region: 'bourgogne',
    gouts: ['doux'],
    occasions: ['reception'],
    conservation: '2 jours dans une boîte hermétique',
    ingredients: [
      { nom: 'Farine', quantite: '30 g', rayon: 'Épicerie' },
      { nom: 'Comté râpé', quantite: '25 g', rayon: 'Crèmerie' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Beurre', quantite: '15 g', rayon: 'Crèmerie' },
      { nom: 'Lait demi-écrémé', quantite: '5 cl', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Portez le lait et le beurre à ébullition, versez la farine d’un coup et remuez jusqu’à ce que la pâte se décolle.',
      'Desséchez-la 1 minute sur le feu, puis laissez tiédir avant d’incorporer l’œuf — sur une pâte brûlante, il cuirait.',
      'Ajoutez le comté, dressez de petits tas à la cuillère sur une plaque.',
      'Enfournez 25 minutes à 190 °C sans ouvrir le four : un courant d’air les fait retomber définitivement.',
    ],
  },
  {
    id: 'quenelles-sauce-nantua',
    titre: 'Quenelles sauce Nantua',
    moment: 'diner',
    minutes: 40,
    kcal: 580,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: [],
    cuisine: 'francaise',
    region: 'lyonnais',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['dimanche'],
    ingredients: [
      { nom: 'Quenelles de brochet', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '10 cl', rayon: 'Crèmerie' },
      { nom: 'Bisque de homard', quantite: '10 cl', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '10 g', rayon: 'Crèmerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites chauffer la bisque avec la crème et laissez réduire 10 minutes à feu doux.',
      'Rangez les quenelles dans un plat beurré en les espaçant : elles doublent de volume.',
      'Nappez de sauce et enfournez 25 minutes à 200 °C.',
      'Servez dès la sortie, avec le riz — elles retombent en refroidissant.',
    ],
    astuce: 'Le plat doit être plus grand qu’il n’en a l’air nécessaire. Serrées, les quenelles se soudent et ne gonflent pas.',
  },
  {
    id: 'salade-lyonnaise',
    titre: 'Salade lyonnaise',
    moment: 'dejeuner',
    minutes: 20,
    kcal: 470,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['rapide'],
    cuisine: 'francaise',
    region: 'lyonnais',
    gouts: ['acidule'],
    typePlat: 'salade',
    occasions: ['semaine'],
    ingredients: [
      { nom: 'Frisée', quantite: '1 poignée généreuse', rayon: 'Fruits et légumes' },
      { nom: 'Œufs', quantite: '1', rayon: 'Crèmerie' },
      { nom: 'Lardons', quantite: '50 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pain de campagne', quantite: '1 tranche', rayon: 'Boulangerie' },
      { nom: 'Vinaigre de vin', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Moutarde', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir les lardons à sec, puis les croûtons de pain dans la graisse rendue.',
      'Déglacez la poêle au vinaigre et versez ce jus chaud sur la frisée : c’est lui la vinaigrette.',
      'Pochez l’œuf 3 minutes dans une eau frémissante.',
      'Dressez la salade, les lardons, les croûtons, et l’œuf poché au centre.',
    ],
    astuce: 'Le jaune coulant fait partie de la sauce. Percez-le à table et mélangez — c’est le geste du plat.',
  },
  {
    id: 'gratin-dauphinois',
    titre: 'Gratin dauphinois',
    moment: 'diner',
    minutes: 90,
    kcal: 480,
    couvre: ['feculent', 'matiere-grasse'],
    tags: ['vegetarien', 'batch'],
    cuisine: 'francaise',
    region: 'savoie',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['dimanche', 'reconfort'],
    regimes: ['vegetarien', 'sans-gluten'],
    conservation: '3 jours au réfrigérateur',
    rechauffage: '20 min à 160 °C à couvert.',
    ingredients: [
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Lait demi-écrémé', quantite: '10 cl', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '5 cl', rayon: 'Crèmerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Noix de muscade', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Beurre', quantite: '5 g', rayon: 'Crèmerie' },
    ],
    etapes: [
      'Coupez les pommes de terre en rondelles de 2 mm et ne les rincez pas : leur amidon est ce qui lie le gratin.',
      'Frottez le plat à l’ail, beurrez-le.',
      'Faites tiédir lait, crème et muscade, puis versez les rondelles dedans et laissez 5 minutes.',
      'Rangez le tout dans le plat en tassant, liquide à hauteur.',
      'Enfournez 1 h 15 à 150 °C. Cuisson lente : à four chaud, le dessus brûle avant que le cœur soit tendre.',
    ],
    astuce: 'Ni fromage ni œuf dans un dauphinois. Avec du fromage, c’est un gratin savoyard — bon aussi, mais autre chose.',
  },
  {
    id: 'tartiflette',
    titre: 'Tartiflette',
    moment: 'diner',
    minutes: 70,
    kcal: 720,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['batch', 'plaisir'],
    cuisine: 'francaise',
    region: 'savoie',
    gouts: ['fume', 'doux'],
    typePlat: 'gratin',
    occasions: ['reconfort', 'reception'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Reblochon', quantite: '60 g', rayon: 'Crèmerie' },
      { nom: 'Lardons fumés', quantite: '50 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc de Savoie', quantite: '5 cl', rayon: 'Épicerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire les pommes de terre à l’eau 20 minutes, puis coupez-les en rondelles épaisses.',
      'Faites revenir lardons et oignon, déglacez au vin blanc.',
      'Mélangez le tout et versez dans un plat.',
      'Coupez le reblochon en deux dans l’épaisseur et posez-le croûte vers le haut : la croûte retient le fromage qui fond dessous.',
      'Enfournez 25 minutes à 200 °C et servez avec la salade.',
    ],
    astuce: 'La salade n’est pas là pour la forme : elle est le seul contrepoids à un plat qui, seul, sature au bout de dix bouchées.',
  },
  {
    id: 'fondue-savoyarde',
    titre: 'Fondue savoyarde',
    moment: 'diner',
    minutes: 30,
    kcal: 690,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['vegetarien', 'plaisir'],
    cuisine: 'francaise',
    region: 'savoie',
    gouts: ['doux'],
    occasions: ['reception', 'reconfort'],
    ingredients: [
      { nom: 'Comté', quantite: '60 g', rayon: 'Crèmerie' },
      { nom: 'Beaufort', quantite: '60 g', rayon: 'Crèmerie' },
      { nom: 'Emmental', quantite: '40 g', rayon: 'Crèmerie' },
      { nom: 'Vin blanc de Savoie', quantite: '8 cl', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Pain de campagne', quantite: '80 g', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Frottez le caquelon avec l’ail coupé, puis versez le vin et faites-le chauffer sans bouillir.',
      'Ajoutez les fromages râpés par poignées, en remuant en huit et jamais en rond — le huit empêche la masse de tourner sur elle-même sans se mélanger.',
      'Poursuivez à feu doux jusqu’à une texture nappante et homogène.',
      'Passez à table et gardez la flamme au minimum.',
    ],
    astuce: 'Trois fromages, trois rôles : le comté pour le goût, le beaufort pour le fondant, l’emmental pour le fil. Un seul fromage donne une fondue qui file mal ou qui tranche.',
  },
  {
    id: 'diots-polenta',
    titre: 'Diots au vin blanc et polenta',
    moment: 'diner',
    minutes: 50,
    kcal: 640,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'savoie',
    gouts: ['fume'],
    typePlat: 'mijote',
    occasions: ['semaine', 'reconfort'],
    ingredients: [
      { nom: 'Diots de Savoie', quantite: '2', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Vin blanc de Savoie', quantite: '15 cl', rayon: 'Épicerie' },
      { nom: 'Polenta', quantite: '50 g crue', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Piquez les diots à la fourchette et faites-les colorer 5 minutes.',
      'Ajoutez oignon et carotte émincés, versez le vin blanc à mi-hauteur.',
      'Couvrez et laissez mijoter 35 minutes à feu doux.',
      'Préparez la polenta en pluie dans de l’eau bouillante salée, en fouettant, puis 10 minutes à feu doux.',
      'Servez les diots sur la polenta, nappés de leur jus.',
    ],
  },
  {
    id: 'aligot',
    titre: 'Aligot et saucisse',
    moment: 'diner',
    minutes: 50,
    kcal: 700,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['plaisir'],
    cuisine: 'francaise',
    region: 'auvergne',
    gouts: ['doux'],
    occasions: ['reconfort', 'dimanche'],
    ingredients: [
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Tomme fraîche', quantite: '80 g', rayon: 'Crèmerie' },
      { nom: 'Crème légère 15 %', quantite: '3 CàS', rayon: 'Crèmerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Saucisse de Toulouse', quantite: '1', rayon: 'Boucherie, poissonnerie' },
    ],
    etapes: [
      'Cuisez les pommes de terre à l’eau, écrasez-les au presse-purée — jamais au mixeur, qui en fait une colle élastique.',
      'Remettez la purée sur feu doux avec la crème et l’ail écrasé.',
      'Incorporez la tomme en lamelles en remuant énergiquement en huit, sans jamais arrêter.',
      'Continuez 8 à 10 minutes : l’aligot est prêt quand il file en ruban depuis la cuillère levée.',
      'Servez avec la saucisse grillée.',
    ],
    astuce: 'Il faut de la tomme fraîche, non affinée. Un cantal vieux ne filera pas, quelle que soit l’énergie qu’on y mette.',
  },
  {
    id: 'truffade',
    titre: 'Truffade',
    moment: 'diner',
    minutes: 40,
    kcal: 660,
    couvre: ['feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'auvergne',
    gouts: ['doux'],
    typePlat: 'poelee',
    occasions: ['reconfort'],
    ingredients: [
      { nom: 'Pommes de terre', quantite: '250 g', rayon: 'Fruits et légumes' },
      { nom: 'Tomme fraîche', quantite: '70 g', rayon: 'Crèmerie' },
      { nom: 'Ail', quantite: '1 gousse', rayon: 'Fruits et légumes' },
      { nom: 'Huile de tournesol', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Coupez les pommes de terre en fines lamelles et faites-les cuire à la poêle à couvert, 20 minutes, en remuant peu.',
      'Écrasez-les grossièrement à la spatule avec l’ail.',
      'Ajoutez la tomme en lamelles et mélangez jusqu’à ce qu’elle fonde et lie le tout.',
      'Laissez prendre 5 minutes sans remuer pour former une croûte au fond, puis retournez sur une assiette.',
    ],
  },
  {
    id: 'ratatouille',
    titre: 'Ratatouille',
    moment: 'diner',
    minutes: 70,
    kcal: 320,
    couvre: ['legume', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique'],
    cuisine: 'francaise',
    region: 'provence',
    gouts: ['herbace', 'doux'],
    typePlat: 'poelee',
    occasions: ['semaine'],
    regimes: ['vegetarien', 'vegan', 'sans-gluten', 'sans-lactose'],
    saisons: ['ete'],
    conservation: '4 jours au réfrigérateur',
    rechauffage: 'À la poêle ou froide, à la cuillère. Elle est meilleure le lendemain.',
    ingredients: [
      { nom: 'Aubergine', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Poivron', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Herbes de Provence', quantite: '1 CàC', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir chaque légume séparément dans l’huile, jusqu’à ce qu’il soit coloré et ferme.',
      'Faites compoter les tomates avec l’oignon 20 minutes à part.',
      'Réunissez le tout, ajoutez les herbes et laissez mijoter 20 minutes à découvert.',
      'Rectifiez le sel en fin de cuisson, quand l’eau est partie.',
    ],
    astuce: 'La cuisson séparée est toute la différence entre une ratatouille et une purée de légumes : chaque légume garde son goût et sa tenue.',
  },
  {
    id: 'bouillabaisse',
    titre: 'Bouillabaisse',
    moment: 'diner',
    minutes: 75,
    kcal: 560,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['une-casserole'],
    cuisine: 'francaise',
    region: 'provence',
    gouts: ['epice', 'herbace'],
    typePlat: 'soupe',
    occasions: ['dimanche', 'reception'],
    ingredients: [
      { nom: 'Poissons de roche variés', quantite: '250 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Fenouil', quantite: '1/2 bulbe', rayon: 'Fruits et légumes' },
      { nom: 'Safran', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '2 gousses', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Pain de campagne', quantite: '1 tranche', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Faites revenir fenouil, oignon et ail dans l’huile, ajoutez les tomates concassées.',
      'Mouillez d’eau bouillante, ajoutez le safran et laissez bouillir franchement 20 minutes : c’est cette ébullition qui lie l’huile et l’eau.',
      'Ajoutez les pommes de terre, 15 minutes.',
      'Plongez les poissons par ordre de fermeté et coupez le feu 8 minutes plus tard.',
      'Servez le bouillon d’abord, avec le pain frotté d’ail, puis les poissons.',
    ],
    astuce: 'Le safran s’ajoute au bouillon, jamais sur le poisson : il a besoin de liquide chaud et de temps pour livrer sa couleur.',
  },
  {
    id: 'daube-provencale',
    titre: 'Daube provençale',
    moment: 'diner',
    minutes: 200,
    kcal: 620,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'provence',
    gouts: ['herbace'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Bœuf à braiser', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Vin rouge', quantite: '20 cl', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Olives noires', quantite: '10', rayon: 'Épicerie' },
      { nom: 'Zeste d’orange', quantite: '1 lanière', rayon: 'Fruits et légumes' },
      { nom: 'Thym et laurier', quantite: '1 branche, 1 feuille', rayon: 'Fruits et légumes' },
      { nom: 'Pâtes', quantite: '60 g crues', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites mariner la viande une nuit dans le vin avec les aromates et le zeste d’orange.',
      'Égouttez, séchez, colorez la viande, puis remettez la marinade filtrée.',
      'Ajoutez les carottes et laissez mijoter 3 heures à couvert, très doucement.',
      'Ajoutez les olives 20 minutes avant la fin — plus tôt, elles rendent le plat amer.',
      'Servez avec les pâtes, arrosées d’un peu de sauce.',
    ],
    astuce: 'Le zeste d’orange est la signature provençale. Prenez-le sans le blanc, qui n’apporte que l’amertume.',
  },
  {
    id: 'pissaladiere',
    titre: 'Pissaladière',
    moment: 'dejeuner',
    minutes: 80,
    kcal: 470,
    couvre: ['feculent', 'legume', 'proteine', 'matiere-grasse'],
    tags: ['batch', 'nomade', 'economique'],
    cuisine: 'francaise',
    region: 'provence',
    gouts: ['doux'],
    typePlat: 'tarte',
    occasions: ['pique-nique', 'reception'],
    ingredients: [
      { nom: 'Pâte à pain', quantite: '80 g', rayon: 'Boulangerie' },
      { nom: 'Oignons', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Anchois à l’huile', quantite: '4 filets', rayon: 'Épicerie' },
      { nom: 'Olives noires', quantite: '8', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Thym', quantite: '1 branche', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Émincez les oignons et faites-les fondre 45 minutes à feu très doux, à couvert : ils doivent devenir une compote blonde, sans jamais colorer fort.',
      'Étalez la pâte, garnissez d’oignons en couche épaisse.',
      'Disposez les anchois en croisillons et les olives dans les losanges.',
      'Enfournez 20 minutes à 200 °C.',
    ],
    astuce: 'Pas de tomate dans une pissaladière niçoise : l’oignon fondu est le plat, et la tomate le noierait.',
  },
  {
    id: 'soupe-au-pistou',
    titre: 'Soupe au pistou',
    moment: 'diner',
    minutes: 60,
    kcal: 400,
    couvre: ['legume', 'feculent', 'proteine', 'matiere-grasse'],
    tags: ['vegetarien', 'batch', 'economique'],
    cuisine: 'francaise',
    region: 'provence',
    gouts: ['herbace'],
    typePlat: 'soupe',
    occasions: ['semaine'],
    regimes: ['vegetarien'],
    saisons: ['ete'],
    conservation: '3 jours au réfrigérateur, pistou à part',
    ingredients: [
      { nom: 'Haricots blancs cuits', quantite: '80 g', rayon: 'Épicerie' },
      { nom: 'Haricots verts', quantite: '80 g', rayon: 'Fruits et légumes' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Pommes de terre', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Pâtes courtes', quantite: '30 g crues', rayon: 'Épicerie' },
      { nom: 'Basilic', quantite: '1 gros bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Ail', quantite: '2 gousses', rayon: 'Fruits et légumes' },
      { nom: 'Parmesan', quantite: '15 g', rayon: 'Crèmerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites cuire tous les légumes en petits dés dans de l’eau salée, 25 minutes.',
      'Ajoutez les pâtes pour les 10 dernières minutes.',
      'Pilez le basilic, l’ail et le parmesan avec l’huile, jusqu’à obtenir une pâte : c’est le pistou.',
      'Servez la soupe brûlante et ajoutez le pistou dans l’assiette, hors du feu.',
    ],
    astuce: 'Le pistou ne cuit jamais. Une seconde d’ébullition et le basilic devient noir et amer.',
  },
  {
    id: 'cassoulet',
    titre: 'Cassoulet',
    moment: 'diner',
    minutes: 180,
    kcal: 780,
    couvre: ['proteine', 'feculent', 'legume'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'languedoc',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'reconfort'],
    conservation: '3 jours au réfrigérateur',
    rechauffage: '30 min à 160 °C, en cassant la croûte une fois.',
    ingredients: [
      { nom: 'Haricots blancs secs', quantite: '80 g', rayon: 'Épicerie' },
      { nom: 'Confit de canard', quantite: '1 cuisse', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Saucisse de Toulouse', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Couenne de porc', quantite: '30 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Concentré de tomate', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites tremper les haricots une nuit, puis cuisez-les 1 heure avec la couenne, l’oignon et la carotte.',
      'Faites dorer la saucisse et réchauffez le confit pour en retirer l’excès de graisse.',
      'Montez le cassoulet en couches dans une terrine : haricots, viandes, haricots, en finissant par les haricots.',
      'Mouillez du bouillon de cuisson à hauteur et enfournez 1 h 30 à 150 °C.',
      'Cassez la croûte à la cuillère trois ou quatre fois pendant la cuisson, en la renfonçant dans le jus.',
    ],
    astuce: 'Casser la croûte n’est pas une coquetterie : c’est ce qui redonne du liquide en surface et forme, au final, une croûte épaisse et fondante au lieu d’une pellicule sèche.',
  },
  {
    id: 'confit-canard-pommes-sarladaises',
    titre: 'Confit de canard et pommes sarladaises',
    moment: 'diner',
    minutes: 45,
    kcal: 740,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['plaisir'],
    cuisine: 'francaise',
    region: 'sud-ouest',
    gouts: ['doux'],
    typePlat: 'roti',
    occasions: ['dimanche', 'fete'],
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Confit de canard', quantite: '1 cuisse', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Ail', quantite: '2 gousses', rayon: 'Fruits et légumes' },
      { nom: 'Persil', quantite: '1 petit bouquet', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Sortez la cuisse de sa graisse et essuyez-la ; réservez une cuillère de graisse pour les pommes de terre.',
      'Faites-la réchauffer côté peau dans une poêle froide, à feu moyen, 15 minutes : la graisse restante fond et la peau croustille.',
      'Faites sauter les pommes de terre en rondelles dans la graisse, 20 minutes, en les retournant peu.',
      'Ajoutez ail et persil hachés à la toute fin, hors du feu.',
      'Servez avec la salade.',
    ],
    astuce: 'La persillade se met au dernier moment. Cuite, elle brûle et devient âcre.',
  },
  {
    id: 'garbure',
    titre: 'Garbure',
    moment: 'diner',
    minutes: 120,
    kcal: 480,
    couvre: ['legume', 'proteine', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'sud-ouest',
    gouts: ['fume'],
    typePlat: 'soupe',
    occasions: ['reconfort', 'semaine'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Manchon de canard confit', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Chou vert', quantite: '1/4', rayon: 'Fruits et légumes' },
      { nom: 'Haricots blancs cuits', quantite: '80 g', rayon: 'Épicerie' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Poireau', quantite: '1', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Faites cuire carottes, poireau et pommes de terre dans un grand volume d’eau, 30 minutes.',
      'Ajoutez le chou blanchi et les haricots, 30 minutes de plus.',
      'Ajoutez le confit pour les 20 dernières minutes, le temps qu’il se détache.',
      'Écrasez quelques pommes de terre dans le bouillon pour l’épaissir.',
    ],
    astuce: 'La garbure doit tenir la cuillère debout, ou presque. Une garbure liquide est une soupe qui n’a pas assez réduit.',
  },
  {
    id: 'poulet-basquaise',
    titre: 'Poulet basquaise',
    moment: 'diner',
    minutes: 60,
    kcal: 540,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'pays-basque',
    gouts: ['epice', 'doux'],
    typePlat: 'mijote',
    occasions: ['semaine', 'dimanche'],
    regimes: ['sans-gluten', 'sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Cuisse de poulet', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poivrons rouges', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Poivrons verts', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Piment d’Espelette', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites dorer le poulet sur toutes ses faces, puis réservez.',
      'Faites revenir oignon et poivrons en lanières 15 minutes, jusqu’à ce qu’ils fondent.',
      'Ajoutez les tomates concassées et le piment d’Espelette.',
      'Remettez le poulet, couvrez et laissez mijoter 30 minutes.',
      'Servez avec le riz.',
    ],
    astuce: 'Le piment d’Espelette parfume plus qu’il ne pique. Le remplacer par du piment fort change la nature du plat.',
  },
  {
    id: 'axoa',
    titre: 'Axoa de veau',
    moment: 'diner',
    minutes: 75,
    kcal: 570,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'pays-basque',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['semaine'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Épaule de veau hachée au couteau', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poivrons verts', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Piment d’Espelette', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Pommes de terre', quantite: '150 g', rayon: 'Fruits et légumes' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir oignon et poivrons taillés en petits dés, 15 minutes.',
      'Ajoutez le veau et laissez-le blanchir sans chercher à le colorer.',
      'Mouillez d’un fond d’eau, ajoutez le piment, couvrez et laissez 45 minutes à feu doux.',
      'Servez avec les pommes de terre vapeur.',
    ],
    astuce: 'La viande est hachée au couteau, en dés, pas au hachoir : c’est ce qui donne à l’axoa sa texture, entre le ragoût et la viande hachée.',
  },
  {
    id: 'piperade',
    titre: 'Pipérade aux œufs',
    moment: 'diner',
    minutes: 35,
    kcal: 420,
    couvre: ['proteine', 'legume', 'feculent', 'matiere-grasse'],
    tags: ['vegetarien', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'pays-basque',
    gouts: ['epice'],
    typePlat: 'poelee',
    occasions: ['semaine'],
    regimes: ['vegetarien', 'sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Poivrons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Tomates', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Œufs', quantite: '2', rayon: 'Crèmerie' },
      { nom: 'Piment d’Espelette', quantite: '1 pincée', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Pain de campagne', quantite: '1 tranche', rayon: 'Boulangerie' },
    ],
    etapes: [
      'Faites fondre oignon et poivrons 15 minutes à l’huile d’olive.',
      'Ajoutez les tomates concassées et le piment, laissez réduire 10 minutes à découvert.',
      'Battez les œufs et versez-les sur les légumes, à feu doux, en remuant comme des œufs brouillés.',
      'Coupez le feu quand ils sont encore crémeux : la chaleur résiduelle finit la cuisson.',
      'Servez avec le pain.',
    ],
  },
  {
    id: 'civet-sanglier',
    titre: 'Civet de sanglier',
    moment: 'diner',
    minutes: 220,
    kcal: 610,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'corse',
    gouts: ['doux'],
    typePlat: 'mijote',
    occasions: ['dimanche', 'fete'],
    conservation: '4 jours au réfrigérateur',
    ingredients: [
      { nom: 'Sanglier', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Vin rouge corsé', quantite: '20 cl', rayon: 'Épicerie' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Carottes', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Baies de genièvre', quantite: '5', rayon: 'Épicerie' },
      { nom: 'Pâtes', quantite: '60 g crues', rayon: 'Épicerie' },
      { nom: 'Huile d’olive', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites mariner la viande 24 heures dans le vin avec les aromates et le genièvre.',
      'Égouttez, séchez soigneusement, puis colorez la viande à feu vif.',
      'Remettez la marinade filtrée et les légumes, couvrez.',
      'Laissez mijoter 3 heures à feu très doux, jusqu’à ce que la viande se défasse à la fourchette.',
      'Servez avec les pâtes.',
    ],
    astuce: 'La marinade sert autant à attendrir qu’à parfumer. Sur un gibier, 24 heures ne sont pas un excès.',
  },
  {
    id: 'colombo-poulet',
    titre: 'Colombo de poulet',
    moment: 'diner',
    minutes: 60,
    kcal: 560,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole'],
    cuisine: 'francaise',
    region: 'antilles',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['semaine', 'dimanche'],
    regimes: ['sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Cuisse de poulet', quantite: '1', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Poudre à colombo', quantite: '1 CàS', rayon: 'Épicerie' },
      { nom: 'Courgette', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Aubergine', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Pommes de terre', quantite: '100 g', rayon: 'Fruits et légumes' },
      { nom: 'Citron vert', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Riz', quantite: '50 g cru', rayon: 'Épicerie' },
      { nom: 'Huile de tournesol', quantite: '1 CàS', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites mariner le poulet 30 minutes avec la poudre à colombo, l’ail et le jus de citron vert.',
      'Faites-le colorer, puis ajoutez les légumes en gros cubes.',
      'Mouillez à hauteur, couvrez, et laissez mijoter 40 minutes.',
      'Ajoutez un trait de citron vert au moment de servir, avec le riz.',
    ],
    astuce: 'Le colombo se réveille à l’acide. Le citron vert de la fin n’est pas décoratif : sans lui, le plat reste plat.',
  },
  {
    id: 'rougail-saucisse',
    titre: 'Rougail saucisse',
    moment: 'diner',
    minutes: 55,
    kcal: 620,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['batch', 'une-casserole', 'economique'],
    cuisine: 'francaise',
    region: 'reunion',
    gouts: ['releve', 'epice'],
    typePlat: 'mijote',
    occasions: ['semaine'],
    regimes: ['sans-gluten', 'sans-lactose'],
    conservation: '3 jours au réfrigérateur',
    ingredients: [
      { nom: 'Saucisses fumées', quantite: '2', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Tomates', quantite: '4', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '2', rayon: 'Fruits et légumes' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Piment', quantite: '1/2', rayon: 'Fruits et légumes' },
      { nom: 'Curcuma', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Riz', quantite: '60 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites bouillir les saucisses 10 minutes et jetez l’eau : elles sont très salées et fumées.',
      'Coupez-les en rondelles et faites-les dorer.',
      'Ajoutez oignons, gingembre, curcuma et piment, puis les tomates concassées.',
      'Laissez mijoter 30 minutes à découvert, jusqu’à ce que la sauce épaississe.',
      'Servez sur le riz.',
    ],
    astuce: 'Le blanchiment préalable n’est pas facultatif : sans lui, le plat est immangeable de sel.',
  },
  {
    id: 'cari-poisson',
    titre: 'Cari de poisson',
    moment: 'diner',
    minutes: 40,
    kcal: 470,
    couvre: ['proteine', 'legume', 'feculent'],
    tags: ['rapide', 'une-casserole'],
    cuisine: 'francaise',
    region: 'reunion',
    gouts: ['epice'],
    typePlat: 'mijote',
    occasions: ['semaine'],
    regimes: ['sans-gluten', 'sans-lactose'],
    ingredients: [
      { nom: 'Filets de poisson blanc', quantite: '150 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Tomates', quantite: '3', rayon: 'Fruits et légumes' },
      { nom: 'Oignons', quantite: '1', rayon: 'Fruits et légumes' },
      { nom: 'Curcuma', quantite: '1 CàC', rayon: 'Épicerie' },
      { nom: 'Gingembre frais', quantite: '1 morceau', rayon: 'Fruits et légumes' },
      { nom: 'Thym', quantite: '1 branche', rayon: 'Fruits et légumes' },
      { nom: 'Riz', quantite: '60 g cru', rayon: 'Épicerie' },
    ],
    etapes: [
      'Faites revenir l’oignon émincé avec le curcuma et le gingembre, 5 minutes.',
      'Ajoutez les tomates et le thym, laissez compoter 15 minutes.',
      'Posez le poisson dessus, couvrez, et laissez cuire 8 minutes sans remuer.',
      'Servez avec le riz et un peu de sauce.',
    ],
    astuce: 'Le poisson ne se remue jamais dans un cari : il se déferait. On l’installe et on le laisse.',
  },
  {
    id: 'brandade-nimes',
    titre: 'Brandade de morue',
    moment: 'diner',
    minutes: 50,
    kcal: 550,
    couvre: ['proteine', 'feculent', 'matiere-grasse'],
    tags: ['batch'],
    cuisine: 'francaise',
    region: 'languedoc',
    gouts: ['doux'],
    typePlat: 'gratin',
    occasions: ['semaine'],
    conservation: '2 jours au réfrigérateur',
    ingredients: [
      { nom: 'Morue dessalée', quantite: '130 g', rayon: 'Boucherie, poissonnerie' },
      { nom: 'Pommes de terre', quantite: '200 g', rayon: 'Fruits et légumes' },
      { nom: 'Lait demi-écrémé', quantite: '8 cl', rayon: 'Crèmerie' },
      { nom: 'Huile d’olive', quantite: '2 CàS', rayon: 'Épicerie' },
      { nom: 'Ail', quantite: '2 gousses', rayon: 'Fruits et légumes' },
      { nom: 'Salade verte', quantite: '1 poignée', rayon: 'Fruits et légumes' },
    ],
    etapes: [
      'Pochez la morue 10 minutes dans du lait coupé d’eau, sans ébullition, puis effeuillez-la en retirant arêtes et peau.',
      'Écrasez les pommes de terre cuites au presse-purée.',
      'Montez la brandade en incorporant l’huile et le lait chaud en alternance, à la spatule.',
      'Ajoutez l’ail écrasé, versez dans un plat et passez 15 minutes à 200 °C.',
    ],
    astuce: 'Dessalez la morue 24 heures au réfrigérateur en changeant l’eau trois fois. C’est la seule étape qui ne se rattrape pas.',
  },
]
